import ProofNetIR

open ProofNetIR
open ProofNetIR.SequentialFigure7

/-!
This file is compiled separately by the trust audit.  Its output is parsed by
`scripts/audit_axioms.py`, so adding a stronger theorem to the public logical
boundary requires an explicit update of that audit rather than a silent trust
expansion.
-/

#print axioms Certificate.check_iff_declarativelyCorrect
#print axioms Graph.IsTree.acyclic
#print axioms Graph.Acyclic.reindex
#print axioms Graph.acyclic_reindex_iff
#print axioms Graph.Acyclic.edges_add_one_le_vertexCount
#print axioms Graph.connected_of_bounded_acyclic_edgeCount
#print axioms Graph.isTree_iff_bounded_connected_acyclic
#print axioms Graph.isEdgeSimpleCycleTraversal_sound
#print axioms Graph.isEdgeSimpleCycleTraversal_complete
#print axioms Graph.hasEdgeSimpleCycle_eq_true_iff
#print axioms Graph.isAcyclic_eq_true_iff
#print axioms Graph.isTreeViaAcyclic_eq_true_iff
#print axioms Graph.isTreeViaAcyclic_eq_isTree
#print axioms Certificate.isCuspFreeTraversal_eq_true_iff
#print axioms Certificate.isCuspFreeCycleTraversal_eq_true_iff
#print axioms Certificate.hasCuspFreeEdgeSimpleCycle_eq_true_iff
#print axioms Certificate.isCuspAcyclic_eq_true_iff
#print axioms Certificate.DeclarativelyCorrect.isCuspAcyclic
#print axioms Certificate.isCuspAcyclic_of_check
#print axioms Certificate.CuspAcyclic.occurrenceSwitching_acyclic
#print axioms Certificate.cuspAcyclic_iff_allOccurrenceSwitchingsAcyclic
#print axioms Certificate.declarativelyCorrect_iff_structural_cuspAcyclic_allConnected
#print axioms Certificate.check_iff_structural_cuspAcyclic_allConnected
#print axioms Certificate.allOccurrenceSwitchingsConnected_of_reference
#print axioms Certificate.check_iff_structural_cuspAcyclic_referenceConnected
#print axioms Certificate.compactCheck_eq_check
#print axioms CutFreeDerivation.infer?_eq_some_iff_build?_conclusions
#print axioms CutFreeDerivation.build?_structurallyWellFormed
#print axioms CutFreeDerivation.build?_switchingCorrect
#print axioms CutFreeDerivation.build?_declarativelyCorrect
#print axioms CutFreeDerivation.build?_check
#print axioms CutFreeDerivation.desequentialize?_conclusionFormulas?
#print axioms CutFreeDerivation.desequentialize?_declarativelyCorrect
#print axioms CutFreeDerivation.desequentialize?_check
#print axioms CutFreeDerivation.desequentialize?_exists_with_labels_of_infer?
#print axioms CutFreeDerivation.desequentialize?_exists_checked_of_infer?
#print axioms CutFreeDerivation.desequentializeChecked?_exists_of_infer?
#print axioms CutFreeDerivation.elaborate?_exists_of_infer?
#print axioms Certificate.sequentialization_of_check
#print axioms Certificate.generallySequentializable
#print axioms Certificate.reindexEquivalent?_eq_true_iff_of_check
#print axioms Certificate.matchingFormulaOrders_complete
#print axioms Certificate.localIdentityCompatible_inverse
#print axioms Certificate.directProofNetEquivalentWitness?_complete
#print axioms Certificate.proofNetEquivalent?_eq_true_iff
#print axioms CutFreeDerivation.CheckedCertificate.sameProofNet?_eq_true_iff
#print axioms Certificate.proofNetEquivalent_iff_canonicalFamily_of_check
#print axioms Certificate.proofNetCanonicalFingerprint?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalFingerprint?_eq
#print axioms Certificate.structuralCode_injective
#print axioms Certificate.proofNetCanonicalCode?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalCode?_eq
#print axioms Certificate.proofNetEquivalent_iff_canonicalCode_of_check
#print axioms Certificate.proofNetCanonicalKey?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalKey?_eq
#print axioms Certificate.proofNetEquivalent_iff_canonicalKey_of_check
#print axioms Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit
#print axioms Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit_of_check
#print axioms Certificate.proofNetEquivalent_of_matchesCanonicalKey
#print axioms Certificate.StructurallyWellFormed.intrinsicTraversalComplete
#print axioms Certificate.StructurallyWellFormed.intrinsicOrderedLinks_perm
#print axioms Certificate.ProofNetEquivalent.intrinsicCanonicalize_eq
#print axioms Certificate.StructurallyWellFormed.intrinsicCanonicalize_proofNetEquivalent
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalize_eq_of_check
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalCode_eq_of_check
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalKey_eq_of_check
#print axioms Certificate.proofNetEquivalent_of_matchesIntrinsicCanonicalKey
#print axioms Certificate.sequentialize_complete
#print axioms Certificate.verifyDerivation?_sound
#print axioms Certificate.verifyDerivation?_complete
#print axioms Certificate.reconstructDerivationWithFuel?_complete
#print axioms Certificate.reconstructDerivation?_sound
#print axioms Certificate.reconstructDerivation?_accepted
#print axioms Certificate.reconstructDerivation?_complete
#print axioms Certificate.reconstructsDerivation_eq_true_iff_check
#print axioms Certificate.reconstructsDerivation_eq_check
#print axioms Certificate.reconstructDerivationWithinLimits_sound
#print axioms Certificate.reconstructDerivationWithinLimits_accepted
#print axioms Certificate.reconstructDerivationWithinLimits_implies_reconstructs
#print axioms UnificationCandidateResult.linkVisitsBound
#print axioms UnificationWorklistCandidateResult.linkAttemptsWithinBudget
#print axioms UnificationStep.link_exists
#print axioms UnificationStep.marks_fired_conclusion
#print axioms UnificationStep.tokenCount_mono
#print axioms UnificationExecution.trans
#print axioms UnificationMarking.ext
#print axioms UnificationMarking.mergeExtension_equivalence
#print axioms UnificationMarking.mergeExtension_congr
#print axioms UnificationMarking.mergeExtension_comm
#print axioms Graph.EdgeSimplePath.exists_traversed_first_boundary_of_start_true
#print axioms Graph.EdgeSimplePath.prefixBefore
#print axioms Graph.EdgeSimplePath.suffixAfter
#print axioms Graph.EdgeSimplePath.uniqueIntersection_of_traversal_split
#print axioms Graph.SimpleWalk.restrictWithSubset
#print axioms Graph.EdgeWalk.toSimpleWalkWithSubset
#print axioms Graph.EdgeWalk.toEdgeSimplePathWithVerticesSubset
#print axioms Graph.EdgeSimplePath.connectEraseAvoiding
#print axioms UnificationMarking.referencePath_has_first_marked_to_unmarked_boundary
#print axioms UnificationMarking.referencePath_has_last_unmarked_to_marked_boundary
#print axioms UnificationMarking.referencePath_has_first_unmarked_to_marked_boundary
#print axioms Certificate.linkLeftRetainedEdges_lookup_origin
#print axioms UnificationMarking.referenceDirectedEdge_origin
#print axioms UnificationMarking.marked_to_unmarked_referenceEdge_connective_origin
#print axioms UnificationState.toMarking_tokenCount
#print axioms UnificationState.toMarking_mark
#print axioms UnificationState.toMarking_sameThread
#print axioms UnificationState.ObservationEquivalent.abstractable
#print axioms UnificationState.ObservationEquivalent.identityParents
#print axioms UnificationState.ObservationEquivalent.toMarking_eq
#print axioms UnificationState.Abstractable.markConclusion
#print axioms UnificationState.OrderedParents.startMarking_representative_eq
#print axioms UnificationState.OrderedParents.startMarking_sameThread_iff
#print axioms UnificationState.Abstractable.startMarking_ordered
#print axioms UnificationState.OrderedParents.toMarking_isFreshToken
#print axioms UnificationState.startMarking_toMarking_mark_ordered
#print axioms UnificationState.startMarking_startStep_ordered
#print axioms UnificationState.markConclusion_toMarking_mark
#print axioms UnificationState.mergeConclusion_toMarking_mark
#print axioms UnificationState.markConclusion_forwardStep
#print axioms UnificationState.forwardToken?_success
#print axioms UnificationState.forwardToken?_refines
#print axioms UnificationState.tokenAt?_some_witness
#print axioms UnificationState.Abstractable.tokenAt?_sameThread_witness
#print axioms UnificationState.Abstractable.tokenAt?_bound
#print axioms UnificationState.Abstractable.tokenAt?_root
#print axioms UnificationState.ComponentsFormulaConsistent.componentAt
#print axioms Certificate.FirstOccurrencePick.exists_of_mem
#print axioms Certificate.FirstOccurrencePick.positional
#print axioms Certificate.FirstOccurrencePick.mem_remaining_of_ne
#print axioms Certificate.FirstOccurrencePick.two_of_mem
#print axioms UnificationState.OrderedParents.setParent_representative
#print axioms UnificationState.OrderedParents.setParent_sameThread
#print axioms UnificationState.OrderedParents.setParent_sameThread_all
#print axioms UnificationState.unifyTokens?_refines
#print axioms SequentialUnification.sourceIndex_size
#print axioms SequentialUnification.StructurallyWellFormed.sourceIndex_lookup_eq_singleton
#print axioms SequentialUnification.sourceIndex_par_mem
#print axioms SequentialUnification.StructurallyWellFormed.sourceIndex_lookup_eq_submitted_par
#print axioms SequentialUnification.mem_sourceIndex_origin
#print axioms SequentialUnification.sourceIndex_sound
#print axioms SequentialUnification.nextAxiomSetTag_eq
#print axioms SequentialUnification.nextAxiomWithFuel?_sound
#print axioms SequentialUnification.nextAxiomWithFuel?_exists_of_structural_clearThrough
#print axioms SequentialUnification.nextAxiomWithFuel?_exists_of_structural_carrierClear
#print axioms SequentialUnification.nextAxiomWithFuel?_tag_trace_invariants
#print axioms SequentialUnification.nextAxiomWithFuel?_touched_tagged
#print axioms SequentialUnification.nextAxiomWithFuel?_tagged_iff_input_or_touched
#print axioms SequentialUnification.nextAxiom?_tagged_iff_input_or_touched
#print axioms SequentialUnification.nextAxiomWithFuel?_threaded_touched_disjoint
#print axioms SequentialUnification.NextAxiomResult.linkIndex_ne_of_input_left_tagged
#print axioms SequentialUnification.NextAxiomResult.threaded_linkIndex_ne
#print axioms SequentialUnification.SourceLeftStep.formulaComplexity_lt
#print axioms SequentialUnification.SourceLeftReachable.formulaComplexity_le
#print axioms SequentialUnification.SourceLeftReachable.eq_or_exists_lastStep
#print axioms SequentialUnification.SourceLeftChain.cons_of_head
#print axioms SequentialUnification.SourceLeftChain.reachable_of_head_last
#print axioms SequentialUnification.nextAxiomWithFuel?_route
#print axioms SequentialUnification.nextAxiom?_route
#print axioms SequentialUnification.NextAxiomRoute.orientedEndpoints?_eq
#print axioms SequentialUnification.DynamicStartResult.refinesStart
#print axioms SequentialUnification.nextAxiomWithFuel?_startReady
#print axioms SequentialUnification.nextAxiom?_startReady
#print axioms SequentialUnification.nextAxiomWithFuel?_traceReady
#print axioms SequentialUnification.nextAxiom?_traceReady
#print axioms SequentialUnification.FreshSourceLeftRun.traceNonempty
#print axioms SequentialUnification.FreshSourceLeftRun.partnerFresh
#print axioms SequentialUnification.FreshSourceLeftRun.partner_not_mem_trace
#print axioms SequentialUnification.FreshSourceLeftRun.exactAxiom
#print axioms SequentialUnification.FreshSourceLeftRun.reachedReady
#print axioms SequentialUnification.FreshSourceLeftRun.partnerReady
#print axioms SequentialUnification.FreshSourceLeftRun.TerminalAxiom.exists_reserveAxiomAt
#print axioms SequentialUnification.FreshSourceLeftRun.execution
#print axioms SequentialUnification.FreshSourceLeftRun.ofExecution
#print axioms SequentialUnification.FreshSourceLeftRun.execution_iff_nonempty
#print axioms SequentialUnification.FreshSourceLeftRun.traceNodup
#print axioms SequentialUnification.FreshSourceLeftRun.traceLast
#print axioms SequentialUnification.FreshSourceLeftRun.traceLength
#print axioms SequentialUnification.FreshSourceLeftRun.traceHead
#print axioms SequentialUnification.FreshSourceLeftRun.sourceLeftChain
#print axioms SequentialUnification.FreshSourceLeftRun.sourceLeftReachable
#print axioms SequentialUnification.FreshSourceLeftRun.traceFresh
#print axioms SequentialUnification.FreshSourceLeftRun.traceReady
#print axioms SequentialUnification.FreshSourceLeftRun.toFreshSourceLeftRoute_nonempty
#print axioms SequentialUnification.SourceLeftRegionVertex.prepend
#print axioms SequentialUnification.SourceLeftRegionVertex.inBounds
#print axioms SequentialUnification.FreshSourceBlocker.prepend
#print axioms Certificate.StructurallyWellFormed.freshSourceLeftRun_or_blocker
#print axioms Certificate.StructurallyWellFormed.freshSourceLeftRun_of_regionAvailable
#print axioms Certificate.OccurrenceDerivation.sourceLeftRegion_owned
#print axioms SequentialFigure7.NewGuard.mate_bound
#print axioms SequentialFigure7.NewGuard.not_sourceLeftReachable_mate_head
#print axioms SequentialFigure7.NewGuard.terminalPartner_ne_head
#print axioms SequentialFigure7.NewGuard.terminalPartner_ne_head_of_declarativelyCorrect
#print axioms SequentialFigure7.sourceLeftRegionVertex_referencePath_avoiding
#print axioms SequentialFigure7.referenceAcyclic_no_tensorBypass
#print axioms SequentialFigure7.SchedulerInvariant.exactMarkedOccurrenceOwner
#print axioms SequentialFigure7.NewGuard.tensorConclusion_not_produced
#print axioms SequentialFigure7.NewGuard.tensorConclusion_not_owned
#print axioms SequentialFigure7.ReadyHeadInput.activeComponent
#print axioms SequentialFigure7.NewGuard.sourceLeftRegion_marked_representative_ne_active
#print axioms SequentialUnification.SourceLeftChain.reachable_to_last_of_mem
#print axioms SequentialFigure7.ReservationEvent.leftEndpoint_sourceLeftRegion_of_touched
#print axioms SequentialFigure7.NewGuard.sourceLeftRegion_formulaComplexity_lt_conclusion
#print axioms SequentialFigure7.CanonicalTagHistory.not_event_touch_of_sameRepresentative
#print axioms SequentialFigure7.FutureWorkAt.mem_queued
#print axioms SequentialFigure7.FutureWorkAt.rawAge_mem_sigma
#print axioms SequentialFigure7.FutureWorkAt.rawAge_lt_nextAge
#print axioms SequentialFigure7.FutureWorkAt.representative_eq_rawAge
#print axioms SequentialFigure7.ReadyHeadInput.futureWorkAt
#print axioms SequentialFigure7.SourceLeftRegionsDisjoint.symm
#print axioms SequentialFigure7.OlderSourceRegionSeparated.not_event_touch_of_lt
#print axioms SequentialFigure7.SourceLeftRegionsDisjoint.eventTouchSeparated
#print axioms SequentialFigure7.ReservationEvent.TouchSeparatedFrom.sourceLeftRegionsDisjoint
#print axioms SequentialFigure7.SourceLeftRegionsDisjoint.iff_eventTouchSeparated
#print axioms SequentialFigure7.OlderSourceRegionSeparated.olderEventTouchSeparated
#print axioms SequentialFigure7.OlderEventTouchSeparated.olderSourceRegionSeparated
#print axioms SequentialFigure7.OlderEventTouchSeparated.iff_olderSourceRegionSeparated
#print axioms
  CanonicalTagHistory.event_touch_active_region_implies_representative_lt
#print axioms
  CanonicalTagHistory.event_touch_active_region_implies_rawAge_lt
#print axioms
  CanonicalTagHistory.event_touchSeparatedFrom_active_sourceLeftRegion_of_olderEventTouchSeparated
#print axioms
  CanonicalTagHistory.active_sourceLeftRegion_tagFresh_of_olderEventTouchSeparated
#print axioms
  CanonicalTagHistory.active_sourceLeftRegion_tagFresh_of_olderSourceRegionSeparated
#print axioms SequentialFigure7.ReservationEvent.touched_candidateConclusion_cases
#print axioms
  CanonicalTagHistory.active_conclusion_touch_implies_head_touch
#print axioms
  CanonicalTagHistory.active_newSourceRegionInput_or_exactMarkedOwner
#print axioms CanonicalTagHistory.active_newEnabled_or_exactMarkedOwner
#print axioms CanonicalTagHistory.active_newEnabled_of_no_exactMarkedOwner
#print axioms SequentialFigure7.empty_olderSourceRegionSeparated
#print axioms SequentialFigure7.InitialReservationStep.olderSourceRegionSeparated
#print axioms SequentialFigure7.FutureWorkAt.beforePrepared
#print axioms SequentialFigure7.PreparedStep.after_representative_eq_before
#print axioms SequentialFigure7.FutureNewCandidateAt.beforePrepared
#print axioms SequentialFigure7.PreparedStep.olderSourceRegionSeparated
#print axioms SequentialFigure7.ConclStep.olderSourceRegionSeparated
#print axioms SequentialFigure7.NopStep.olderSourceRegionSeparated
#print axioms
  SequentialFigure7.OlderEventTouchSeparated.strict_candidateConclusion_untouched
#print axioms SequentialFigure7.empty_olderEventFutureWorkTouchSeparated
#print axioms
  SequentialFigure7.InitialReservationStep.olderEventFutureWorkTouchSeparated
#print axioms
  SequentialFigure7.PreparedStep.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.ConclStep.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.NopStep.olderEventFutureWorkTouchSeparated
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath_avoiding_of_strict
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentInterval_referencePath_avoiding_of_lastOlder
#print axioms SequentialFigure7.CanonicalTagHistory.strictOlderSigmaSplit
#print axioms
  SequentialFigure7.CanonicalTagHistory.sameRepresentative_conclusionTouch_decomposition
#print axioms
  SequentialFigure7.ReservationEvent.touched_parConclusion_decomposition
#print axioms SequentialFigure7.ReservationEvent.touched_parConclusion_cases
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath_avoiding_of_equal_storedRight
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentEdge_equal_boundary_dichotomy
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentEdge_parConclusion_dichotomy
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentInterval_parConclusion_dichotomy
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentInterval_parConclusion_localizedDichotomy
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceOutcome
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryTargetOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryTargetOutcome
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryMarkedOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryMarkedOutcome
#print axioms
  SequentialFigure7.ActiveCarrierExternalReentryMarkedHistoricalTarget.mateSeparated
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryMateSeparatedOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryMateSeparatedOutcome
#print axioms
  SequentialFigure7.ActiveCarrierExternalReentryMarkedMateSeparatedTarget.temporalTarget
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryMarkedTemporalOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryMarkedTemporalOutcome
#print axioms
  SequentialFigure7.ActiveCarrierExternalReentryMarkedMateSeparatedTemporalTarget.continuationExitTarget
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryMarkedContinuationExitOutcome
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryMarkedContinuationExitOutcome
#print axioms
  SequentialFigure7.MarkedConclusionChain.terminal_marked_of_ne
namespace ProofNetIR.SequentialFigure7
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
#print axioms nopNoExactReturnTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
end ProofNetIR.SequentialFigure7
#print axioms
  SequentialFigure7.NopStep.commitmentInterval_parTraceReentryMarkedContinuationNoExactReturnOutcome
#print axioms
  SequentialFigure7.MarkedConclusionChain.firstRepresentativeDescent_of_ne
namespace ProofNetIR.SequentialFigure7
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
#print axioms firstDescentTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
end ProofNetIR.SequentialFigure7
#print axioms
  SequentialFigure7.WaitStep.commitmentInterval_parTraceReentryMarkedContinuationFirstDescentOutcome
#print axioms
  SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.first_rawMarked
#print axioms
  SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.second_rawMarked
#print axioms
  SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.vertex_ne
#print axioms
  SequentialFigure7.CanonicalTagHistory.rawMarkedPremisesBefore
#print axioms
  SequentialFigure7.MarkedConclusionChainFirstRepresentativeDescent.causalDescent
namespace ProofNetIR.SequentialFigure7
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationFirstDescentTarget
#print axioms causalDescentTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationFirstDescentTarget
namespace WaitStep
#print axioms commitmentInterval_parTraceReentryMarkedContinuationCausalDescentOutcome
end WaitStep
end ProofNetIR.SequentialFigure7
namespace ProofNetIR.SequentialFigure7
namespace CanonicalTagHistory.RawMarkedBefore
#print axioms trans
#print axioms asymmetric
end CanonicalTagHistory.RawMarkedBefore
#print axioms MarkedConclusionChain.rawMarkedBefore_or_eq
namespace MarkedConclusionChainFirstCausalDescent
#print axioms originBeforeTerminal
#print axioms mateBeforeTerminal
end MarkedConclusionChainFirstCausalDescent
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCausalDescentTarget
#print axioms terminalCausalTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCausalDescentTarget
namespace WaitStep
#print axioms commitmentInterval_parTraceReentryMarkedContinuationTerminalCausalOutcome
end WaitStep
end ProofNetIR.SequentialFigure7
namespace ProofNetIR.SequentialFigure7
namespace CanonicalTagHistory.RawMarkedBefore
#print axioms total_of_vertex_ne
#print axioms eq_or_before_or_after
end CanonicalTagHistory.RawMarkedBefore
#print axioms ContinuationExit.outerTerminalCausalOutcome
namespace MarkedConclusionChainFirstCausalDescent
#print axioms siblingExitOuterTerminalCausalOutcome
end MarkedConclusionChainFirstCausalDescent
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationTerminalCausalTarget
#print axioms siblingExitCausalTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationTerminalCausalTarget
namespace WaitStep
#print axioms commitmentInterval_parTraceReentryMarkedContinuationSiblingExitCausalOutcome
end WaitStep
end ProofNetIR.SequentialFigure7
#print axioms
  SequentialFigure7.MarkedConclusionChain.rawReturnCyclicReduction
#print axioms
  SequentialFigure7.MarkedConclusionChain.rawReturnCyclicJunctionReduction
namespace ProofNetIR.SequentialFigure7
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
#print axioms continuationCyclicReductionTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget
namespace ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCyclicReductionTarget
#print axioms cyclicJunctionTarget
end ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCyclicReductionTarget
end ProofNetIR.SequentialFigure7
#print axioms
  SequentialFigure7.CanonicalTagHistory.strictOlder_commitmentPath_or_advance_or_equalCallbackFailure
#print axioms
  SequentialFigure7.CanonicalTagHistory.strictOlder_commitmentPath_or_equalCallbackFailure
#print axioms
  SequentialFigure7.CanonicalTagHistory.no_strictOlder_activeMateEventAnchor
#print axioms
  SequentialFigure7.CanonicalTagHistory.event_touchSeparatedFrom_active_sourceLeftRegion
#print axioms
  SequentialFigure7.SchedulerInvariant.exactMarkedOccurrenceOwner_iff_exists_rawMark
#print axioms SequentialFigure7.empty_olderRawMarkedRegionSeparated
#print axioms
  SequentialFigure7.InitialReservationStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.PreparedStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.ConclStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.NopStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.NewGuard.marked_representative_le_active
#print axioms
  SequentialFigure7.OlderRawMarkedRegionSeparated.active_sourceLeftRegion_no_rawMark
#print axioms SequentialFigure7.OlderRawMarkedRegionSeparated.active_clearOwner
#print axioms
  SequentialFigure7.CanonicalTagHistory.active_sourceLeftRegion_no_rawMark
#print axioms
  SequentialFigure7.CanonicalTagHistory.active_sourceLeftRegion_no_exactMarkedOwner
#print axioms
  SequentialFigure7.CanonicalTagHistory.active_sourceLeftRegion_tagFresh
#print axioms
  SequentialFigure7.CanonicalTagHistory.active_newSourceRegionInput
#print axioms SequentialFigure7.CanonicalTagHistory.active_newEnabled
#print axioms
  CanonicalTagHistory.readyHead_priorityEnabled_or_markedTensorPredecessorGap
#print axioms
  ReachableByImplementedDispatcher.readyHead_dispatch_or_markedTensorPredecessorGap
#print axioms
  SequentialFigure7.OlderMarkedTensorPredecessorInvariant.readyHead_predecessor_of_boundary_lt
#print axioms
  SequentialFigure7.empty_olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.InitialReservationStep.olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.PreparedStep.olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.ConclStep.olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.NopStep.olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.CanonicalTagHistory.new_olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.CanonicalTagHistory.wait_olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.CanonicalTagHistory.markedMate_sigmaImmediatePredecessor_of_childAnchor
#print axioms
  SequentialFigure7.CanonicalTagHistory.forward_olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.CanonicalTagHistory.unifyPayload_olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.CanonicalTagHistory.olderMarkedTensorPredecessorInvariant
#print axioms
  SequentialFigure7.ExecutedHistory.olderMarkedTensorPredecessorInvariant
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.readyHead_dispatch
#print axioms
  SequentialFigure7.SchedulerInvariant.no_readyHead_iff_activeTopDrained
#print axioms
  SequentialFigure7.ReachableByImplementedDispatcher.dispatch_or_activeTopDrained
#print axioms SequentialFigure7.empty_activeTopMarkedNonconclusionDebt
#print axioms
  SequentialFigure7.InitialReservationStep.activeTopMarkedNonconclusionDebt
#print axioms SequentialFigure7.NewStep.activeTopMarkedNonconclusionDebt
#print axioms SequentialFigure7.ConclStep.activeTopMarkedNonconclusionDebt
#print axioms
  SequentialFigure7.ForwardStep.activeTopMarkedNonconclusionDebt_of_created_not_conclusion
#print axioms
  SequentialFigure7.UnifyPayloadStep.activeTopMarkedNonconclusionDebt_of_created_not_conclusion
#print axioms
  SequentialFigure7.SchedulerInvariant.allMarked_of_activeTopDrained_of_nonconclusionDebt
#print axioms
  SequentialFigure7.PreparedStep.activeTopMarkedNonconclusionDebt_iff_selectedAway
#print axioms
  SequentialFigure7.NopStep.activeTopMarkedNonconclusionDebt_iff_selectedAway
#print axioms
  SequentialFigure7.WaitStep.activeTopMarkedNonconclusionDebt_iff_selectedAway
#print axioms
  SequentialFigure7.ForwardStep.activeTopMarkedNonconclusionDebt_iff_tailLaw_of_created_conclusion
#print axioms
  SequentialFigure7.UnifyPayloadStep.activeTopMarkedNonconclusionDebt_iff_tailLaw_of_created_conclusion
#print axioms
  SequentialFigure7.NopStep.activeTopMarkedNonconclusionDebt_iff_readyTailNonconclusion
#print axioms
  SequentialFigure7.WaitStep.activeTopMarkedNonconclusionDebt_iff_readyTailNonconclusion
#print axioms
  SequentialFigure7.CanonicalTagHistory.activeTopMarkedNonconclusionDebt_of_tailLaw
#print axioms
  SequentialFigure7.ActiveCarrierParentEscape.authenticMarkedPremise
#print axioms
  SequentialFigure7.ReadyHeadInput.readyTail_nonconclusion_or_parentEscape
#print axioms
  SequentialFigure7.ReadyHeadInput.parentEscape_of_no_readyTail
#print axioms
  SequentialFigure7.ActiveCarrierParentEscape.temporalResidual_of_no_readyTail
#print axioms
  SequentialFigure7.CanonicalTagHistory.ActiveCarrierTensorSameBoundaryResidual.temporalOutcome
#print axioms
  SequentialFigure7.ActiveCarrierParentTemporalResidual.temporalOutcome
#print axioms
  SequentialFigure7.ActiveCarrierParentExternalTemporalOutcome.temporalOutcome
#print axioms
  SequentialFigure7.NopStep.externalParentTemporalOutcome_of_no_readyTail
#print axioms
  SequentialFigure7.WaitStep.externalParentTemporalOutcome_of_no_readyTail
#print axioms
  SequentialFigure7.CanonicalTagHistory.strictOlderCommitmentSplit_to_top
#print axioms
  SequentialFigure7.ActiveCarrierParentExternalTemporalOutcome.commitmentOutcome
#print axioms
  SequentialFigure7.ActiveCarrierParentExternalCommitmentOutcome.endpointCrossing
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentInterval_referencePath
#print axioms
  SequentialFigure7.ActiveCarrierParentExternalCommitmentOutcome.reentryOutcome
#print axioms
  Certificate.OccurrenceDerivation.connectivePremises_owned_of_conclusion_owned
#print axioms
  Certificate.OccurrenceDerivation.connectiveConclusion_owned_of_premise_owned_not_frontier
#print axioms SequentialFigure7.submittedPremise_not_conclusion
#print axioms SequentialFigure7.ActiveCarrierExternalEndpointReentry.targetStatus
#print axioms
  SequentialFigure7.ActiveCarrierExternalEndpointReentry.targetFailureStatus
#print axioms
  SequentialFigure7.ActiveCarrierExternalEndpointReentry.targetFailureHistoricalStatus
#print axioms
  SequentialFigure7.ActiveCarrierExternalEndpointReentryAvoiding.markedHistoricalTarget
#print axioms SequentialFigure7.empty_markedNonconclusionContinuation
#print axioms
  SequentialFigure7.InitialReservationStep.markedNonconclusionContinuation
#print axioms SequentialFigure7.FutureWorkAt.afterPreparedOrSelected
#print axioms SequentialFigure7.NopStep.selectedContinuationCredit
#print axioms SequentialFigure7.WaitStep.createdConclusionFutureWorkAt
#print axioms SequentialFigure7.WaitStep.selectedContinuationCredit
#print axioms SequentialFigure7.NewStep.selectedContinuationCredit
#print axioms SequentialFigure7.ForwardStep.createdConclusionFutureWorkAt
#print axioms SequentialFigure7.ForwardStep.selectedContinuationCredit
#print axioms
  SequentialFigure7.UnifyPayloadStep.createdConclusionFutureWorkAt
#print axioms SequentialFigure7.UnifyPayloadStep.selectedContinuationCredit
#print axioms
  SequentialFigure7.DispatchTagEvidence.newlyMarkedContinuationCredit
#print axioms SequentialFigure7.ConclStep.continuationCredit
#print axioms SequentialFigure7.NopStep.continuationCredit
#print axioms SequentialFigure7.NewStep.continuationCredit
#print axioms SequentialFigure7.WaitStep.continuationCredit
#print axioms SequentialFigure7.ForwardStep.continuationCredit
#print axioms SequentialFigure7.UnifyPayloadStep.continuationCredit
#print axioms SequentialFigure7.DispatchTagEvidence.oldContinuationCredit
#print axioms
  SequentialFigure7.DispatchTagEvidence.markedNonconclusionContinuation
#print axioms
  SequentialFigure7.CanonicalTagHistory.markedNonconclusionContinuation
#print axioms
  SequentialFigure7.MarkedNonconclusionContinuation.continuationExit
#print axioms
  SequentialFigure7.FutureWorkAt.rawAge_lt_active_of_activeTopDrained
#print axioms SequentialFigure7.ContinuationExit.elim_of_activeTopDrained
#print axioms SequentialFigure7.LocalizedContinuationExit.continuationExit
#print axioms
  SequentialFigure7.activeTopMarkedNonconclusionDebt_of_continuationExitLocalized
#print axioms
  SequentialFigure7.SchedulerInvariant.allMarked_of_activeTopDrained_of_continuationExitLocalized
#print axioms
  SequentialFigure7.WaitStep.not_activeTopContinuationExitLocalized
#print axioms SequentialFigure7.NewStep.after_representative_eq_markedMiddle
#print axioms SequentialFigure7.FutureWorkAt.beforeNewOrInserted
#print axioms SequentialFigure7.NewStep.freshEvent_not_strictly_older
#print axioms SequentialFigure7.NewStep.olderSourceRegionSeparated_of_created
#print axioms SequentialFigure7.NewStep.olderEventFutureWorkTouchSeparated
#print axioms
  SequentialFigure7.NewStep.created_sourceRegion_not_selected_of_structural_acyclic
#print axioms SequentialFigure7.NewStep.created_sourceRegion_not_selected
#print axioms SequentialFigure7.NewStep.no_middle_futureWork_at_fresh
#print axioms SequentialFigure7.NewStep.retained_mark_strictly_older_than_fresh
#print axioms
  SequentialFigure7.NewStep.created_rawMarksSeparatedFrom_of_retained
#print axioms SequentialFigure7.NewStep.olderRawMarkedRegionSeparated
#print axioms SequentialSchedulerBridge.WaitDestinationStep.after_representative_eq_before
#print axioms SequentialFigure7.FutureWorkAt.beforeWaitOrInserted
#print axioms SequentialFigure7.WaitStep.olderSourceRegionSeparated_of_created
#print axioms
  SequentialFigure7.WaitStep.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.WaitStep.createdHeadTouchSeparated
#print axioms
  SequentialFigure7.WaitStep.olderEventFutureWorkTouchSeparated_of_structural
#print axioms SequentialFigure7.WaitStep.destination_representative_lt_selected
#print axioms
  SequentialFigure7.WaitStep.created_rawMarksSeparatedFrom_of_retained
#print axioms SequentialFigure7.WaitStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.ForwardStep.after_representative_eq_prepared
#print axioms SequentialFigure7.FutureWorkAt.beforeForwardOrInserted
#print axioms SequentialFigure7.ForwardStep.olderSourceRegionSeparated_of_created
#print axioms
  SequentialFigure7.ForwardStep.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.ForwardStep.createdHeadTouchSeparated
#print axioms
  SequentialFigure7.ForwardStep.olderEventFutureWorkTouchSeparated_of_structural
#print axioms
  SequentialFigure7.ForwardStep.created_rawMarksSeparatedFrom_of_retained
#print axioms SequentialFigure7.ForwardStep.olderRawMarkedRegionSeparated
#print axioms SequentialFigure7.UnifyPayloadStep.after_representative_eq_prepared_if
#print axioms SequentialFigure7.FutureNewCandidateAt.rawAge_le_previousBoundary_of_unifyPayload
#print axioms SequentialFigure7.FutureWorkAt.beforeUnifyPayloadOrMovedOrCreated
#print axioms SequentialFigure7.UnifyPayloadStep.olderSourceRegionSeparated_of_created
#print axioms
  SequentialFigure7.UnifyPayloadStep.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.UnifyPayloadStep.createdConclusionTouchSeparated
#print axioms SequentialFigure7.UnifyPayloadStep.createdHeadTouchSeparated
#print axioms
  SequentialFigure7.UnifyPayloadStep.olderEventFutureWorkTouchSeparated_of_structural
#print axioms SequentialFigure7.UnifyPayloadStep.olderRawMarkedRegionSeparated
#print axioms
  SequentialFigure7.CanonicalTagHistory.olderEventFutureWorkTouchSeparated
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshTagBlocker
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshRawBlocker
#print axioms SequentialFigure7.CanonicalTagHistory.classifyVisitedFreshRawBlocker
#print axioms SequentialFigure7.CanonicalTagHistory.classifyVisitedFreshBlocker
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshRawBlocker_of_referenceAcyclic
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshBlocker_of_referenceAcyclic
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker_of_referenceAcyclic
#print axioms SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker_of_declarativelyCorrect
#print axioms SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_or_obstruction
#print axioms SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_of_no_obstruction
#print axioms SequentialFigure7.CanonicalTagHistory.newInputNecessary_of_no_sourceLeftObstruction
#print axioms SequentialFigure7.CanonicalTagHistory.newEnabled_of_no_sourceLeftObstruction
#print axioms SequentialUnification.SourceLeftChain.reachable_of_head_mem
#print axioms SequentialUnification.NextAxiomRoute.touched_sourceLeftRegion
#print axioms SequentialFigure7.CanonicalTagHistory.touched_nonempty_origin
#print axioms SequentialFigure7.CanonicalTouchOrigin.reservationRegion
#print axioms SequentialFigure7.ReservationSearchEvent.touched_sourceLeftRegion
#print axioms SequentialFigure7.ReservationEvent.touched_sourceLeftRegion
#print axioms SequentialUnification.FreshSourceLeftRun.sourceLeftRegion_touched
#print axioms SequentialFigure7.ReservationEvent.sourceLeftRegion_touched
#print axioms SequentialFigure7.ReservationEvent.touched_iff_sourceLeftRegion
#print axioms SequentialFigure7.NewStep.activeRawAge_lt_reservationRawAge
#print axioms SequentialFigure7.DispatchTagEvidence.range_append_reservationEvents
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_rawAges
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_length
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_getElem?_rawAge
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_eventAtRawAge
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_linkIndices
#print axioms SequentialFigure7.CanonicalTouchOrigin.reservationLedger_event
#print axioms SequentialFigure7.CanonicalTagHistory.touched_reservationLedger_event
#print axioms SequentialFigure7.CanonicalTagHistory.commitmentSpine
#print axioms CutFreeDerivation.pick?_source_unique
#print axioms CutFreeDerivation.reorder?_source_unique
#print axioms Certificate.OccurrenceDerivation.owned_unique
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_realized
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_finalComponent
#print axioms SequentialFigure7.CanonicalTagHistory.reservationLedger_axiomEndpoints_accounted
#print axioms SequentialFigure7.CanonicalTagHistory.rawMarked_reservationEvent_referenceAnchors
#print axioms SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath
#print axioms SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath_avoiding
#print axioms
  SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath_avoiding_parConclusion
#print axioms SequentialFigure7.CanonicalTagHistory.commitmentInterval_referencePath_avoiding
#print axioms SequentialFigure7.carrierFresh
#print axioms SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_carrier_not_touched
#print axioms SequentialFigure7.carrier_not_exactMarkedOccurrenceOwner
#print axioms ConsumerIndex.build_size
#print axioms ConsumerIndex.build_origin
#print axioms ConsumerIndex.build_complete
#print axioms ConsumerIndex.build_sound
#print axioms ConsumerIndex.build_isComplete
#print axioms ConsumerIndex.Sound.origin
#print axioms ConsumerIndex.build_members_eq
#print axioms ConsumerIndex.build_singleton
#print axioms ConsumerIndex.uniqueConsumer?_eq_some_iff
#print axioms ConsumerIndex.build_uniqueConsumer?_eq_some
#print axioms tensorBelow?_eq_some_iff
#print axioms tensorBelow?_consumer
#print axioms tensorBelow?_link
#print axioms tensorBelow?_wellFormed
#print axioms tensorBelow?_premise
#print axioms tensorBelow?_mate_ne
#print axioms Certificate.tensorBelow?_eq_some_iff
#print axioms Certificate.tensorBelow?_consumer
#print axioms Certificate.tensorBelow?_link
#print axioms Certificate.tensorBelow?_wellFormed
#print axioms Certificate.tensorBelow?_premise
#print axioms Certificate.tensorBelow?_mate_ne
#print axioms Certificate.mem_worklistConsumers_of_premise
#print axioms Certificate.mem_worklistConsumers_origin
#print axioms Certificate.mem_worklistConsumers_submitted_connective
#print axioms Certificate.worklistConsumers_members_eq
#print axioms SequentialSchedulerState.WaitingCell.undefined_ne_initialized_empty
#print axioms SequentialSchedulerState.SigmaAgePartition.empty
#print axioms SequentialSchedulerState.SigmaAgePartition.reserveInitial
#print axioms SequentialSchedulerState.SigmaAgePartition.appendFresh
#print axioms SequentialSchedulerState.sigmaBoundary?_append_fresh_old
#print axioms SequentialSchedulerState.sigmaBoundary?_popActive_of_lt
#print axioms SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_append_fresh_self
#print axioms SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_top
#print axioms SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_top_of_le
#print axioms SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_popActive_eq_previous_of_active_le
#print axioms SequentialSchedulerState.sigmaBoundary?_mem
#print axioms SequentialSchedulerState.sigmaBoundary?_le
#print axioms SequentialSchedulerState.sigmaBoundary?_greatest
#print axioms SequentialSchedulerState.SigmaAgePartition.boundary_exists
#print axioms SequentialSchedulerState.sigmaBoundary_unique_of_greatest
#print axioms SequentialSchedulerState.SequentialStackState.WellShaped.waiting_lookup_exists
#print axioms SequentialSchedulerState.SequentialStackState.empty_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.popReadyMark?_ok_iff
#print axioms SequentialSchedulerState.SequentialStackState.popReadyMark?_exact
#print axioms SequentialSchedulerState.SequentialStackState.popReadyMark?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.AllMarksUndefined.lookup
#print axioms SequentialSchedulerState.SequentialStackState.AllWaitingUndefined.lookup
#print axioms SequentialSchedulerState.SequentialStackState.initEnqueue?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.initEnqueue?_exact
#print axioms SequentialSchedulerState.SequentialStackState.initEnqueue?_endpoint_unmarked
#print axioms SequentialSchedulerState.SequentialStackState.initEnqueue?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.newEnqueue?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.newEnqueue?_exact
#print axioms SequentialSchedulerState.SequentialStackState.newEnqueue?_waiting_of_ne
#print axioms SequentialSchedulerState.SequentialStackState.newEnqueue?_endpoint_unmarked
#print axioms SequentialSchedulerState.SequentialStackState.newEnqueue?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.active_undefined
#print axioms SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.payload_boundary_lt_previous_of_ne
#print axioms SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.payload_boundary_lt_previous
#print axioms SequentialSchedulerState.SequentialStackState.empty_operationalWaitingDomain
#print axioms SequentialSchedulerState.SequentialStackState.initEnqueue?_operationalWaitingDomain
#print axioms SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_exact
#print axioms SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_endpoint_unmarked
#print axioms SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_operationalWaitingDomain
#print axioms Certificate.UnificationComponent.axiom?_success
#print axioms Certificate.UnificationComponent.axiom?_formulaConsistent
#print axioms Certificate.reserveAxiomAt?_exact
#print axioms Certificate.reserveAxiomAt?_endpoint_unmarked
#print axioms Certificate.reserveAxiomAt?_componentsParentsAligned
#print axioms Certificate.reserveAxiomAt?_orderedParents
#print axioms Certificate.reserveAxiomAt?_abstractable
#print axioms Certificate.reserveAxiomAt?_componentsFormulaConsistent
#print axioms Certificate.reserveAxiomAt?_counterAligned
#print axioms Certificate.reserveAxiomAt?_old_representative
#print axioms Certificate.reserveAxiomAt?_fresh_representative
#print axioms Certificate.reserveAxiomAt?_tokenAt_eq
#print axioms Certificate.reserveAxiomAt?_componentAt?_of_some
#print axioms UnificationState.markReadyRaw?_ok_iff
#print axioms UnificationState.markReadyRaw?_markOutOfBounds_iff
#print axioms UnificationState.markReadyRaw?_alreadyMarked_iff
#print axioms UnificationState.markReadyRaw?_exact
#print axioms UnificationState.markReadyRaw?_carriers
#print axioms UnificationState.markReadyRaw?_counters
#print axioms UnificationState.markReadyRaw?_orderedParents
#print axioms UnificationState.markReadyRaw?_abstractable
#print axioms UnificationState.markReadyRaw?_componentsFormulaConsistent
#print axioms SequentialSchedulerBridge.RealizesSigma.rawAgeAt?_eq_assignedToken?
#print axioms SequentialSchedulerBridge.initial_realizesSigma
#print axioms SequentialSchedulerBridge.empty_reservationInvariant
#print axioms SequentialSchedulerBridge.initializeReservation?_some_iff
#print axioms SequentialSchedulerBridge.reserveNewAxiom?_some_iff
#print axioms SequentialSchedulerBridge.InitialReservationStep.route
#print axioms SequentialSchedulerBridge.InitialReservationStep.linkIndex_ne_next
#print axioms SequentialSchedulerBridge.NewReservationStep.route
#print axioms SequentialSchedulerBridge.NewReservationStep.linkIndex_ne
#print axioms SequentialSchedulerBridge.init_reserve_carrier_realizesSigma
#print axioms SequentialSchedulerBridge.init_reserve_route_exact
#print axioms SequentialSchedulerBridge.init_reserve_route_fields
#print axioms SequentialSchedulerBridge.InitialReservationStep.reservationInvariant
#print axioms SequentialSchedulerBridge.new_reserve_carrier_realizesSigma
#print axioms SequentialSchedulerBridge.new_reserve_route_exact
#print axioms SequentialSchedulerBridge.new_reserve_route_fields
#print axioms SequentialSchedulerBridge.NewReservationStep.reservationInvariant
#print axioms SequentialSchedulerBridge.popReadyMark_markReadyRaw_realizesSigma
#print axioms SequentialSchedulerBridge.popReadyMark_markReadyRaw_reservationInvariant
#print axioms SequentialSchedulerBridge.empty_schedulerInvariant
#print axioms SequentialSchedulerBridge.SchedulerInvariant.frontier_unmarked_mem_queued
#print axioms SequentialSchedulerBridge.SchedulerInvariant.unmarked_liveFrontier_mem_queued
#print axioms SequentialSchedulerBridge.SchedulerInvariant.owned_unmarked_mem_queued
#print axioms SequentialSchedulerBridge.InitialReservationStep.componentDomainExact
#print axioms SequentialSchedulerBridge.InitialReservationStep.reached_ne_partner
#print axioms SequentialSchedulerBridge.InitialReservationStep.liveFrontiersNodup
#print axioms SequentialSchedulerBridge.InitialReservationStep.queuedVerticesNodup
#print axioms SequentialSchedulerBridge.InitialReservationStep.queuedVerticesUnmarked
#print axioms SequentialSchedulerBridge.InitialReservationStep.readyBucketFrontierExact
#print axioms SequentialSchedulerBridge.InitialReservationStep.producedPremisesMarked
#print axioms SequentialSchedulerBridge.InitialReservationStep.waitingSpanExact
#print axioms SequentialSchedulerBridge.InitialReservationStep.pendingPremisesCoveredExceptReady
#print axioms SequentialSchedulerBridge.InitialReservationStep.firedCounterExact
#print axioms SequentialSchedulerBridge.InitialReservationStep.schedulerInvariant
#print axioms SequentialFigure7.PreparedStep.schedulerInvariant
#print axioms SequentialFigure7.PreparedStep.owned_unmarked_mem_after_queued
#print axioms SequentialFigure7.ConclStep.schedulerInvariant
#print axioms SequentialFigure7.concl?_schedulerInvariant
#print axioms SequentialFigure7.NopStep.schedulerInvariant
#print axioms SequentialFigure7.nop?_schedulerInvariant
#print axioms SequentialFigure7.new?_some_iff
#print axioms SequentialFigure7.NewStep.tensorValid
#print axioms SequentialFigure7.NewStep.mate_unmarked
#print axioms SequentialFigure7.NewStep.route
#print axioms SequentialFigure7.NewStep.markedMiddle_reservationInvariant
#print axioms SequentialFigure7.NewStep.reservationInvariant
#print axioms SequentialFigure7.new?_reservationInvariant
#print axioms SequentialFigure7.NewStep.markedMiddle_schedulerInvariant
#print axioms SequentialFigure7.NewStep.componentForestProvenance
#print axioms SequentialFigure7.NewStep.componentDomainExact
#print axioms SequentialFigure7.NewStep.liveFrontiersNodup
#print axioms SequentialFigure7.NewStep.readyBucketFrontierExact
#print axioms SequentialFigure7.NewStep.queuedVerticesNodup
#print axioms SequentialFigure7.NewStep.queuedVerticesUnmarked
#print axioms SequentialFigure7.NewStep.producedPremisesMarked
#print axioms SequentialFigure7.NewStep.firedCounterExact
#print axioms SequentialFigure7.NewStep.waitingSpanExact
#print axioms SequentialFigure7.NewStep.pendingPremisesCoveredExceptReady
#print axioms SequentialFigure7.NewStep.schedulerInvariant
#print axioms SequentialFigure7.new?_schedulerInvariant
#print axioms SequentialFigure7.TagsExtend.refl
#print axioms SequentialFigure7.TagsExtend.trans
#print axioms SequentialFigure7.initial_output_tags_eq
#print axioms SequentialFigure7.initial_tagsExtend
#print axioms SequentialFigure7.NewStep.output_tags_eq
#print axioms SequentialFigure7.NewStep.tagsExtend
#print axioms SequentialFigure7.InitNewHistory.reservationInvariant
#print axioms SequentialFigure7.InitNewHistory.tagged_iff_touched
#print axioms SequentialFigure7.InitNewHistory.touched_disjoint_next
#print axioms SequentialFigure7.InitNewHistory.mem_linkIndices_witness
#print axioms SequentialFigure7.InitNewHistory.linkIndices_nodup
#print axioms SequentialFigure7.InitNewHistory.length_eq_nextAge
#print axioms SequentialFigure7.InitNewHistory.length_eq_startedAxioms
#print axioms SequentialFigure7.reachable_empty
#print axioms SequentialFigure7.reachable_of_initializeReservation?_eq_some
#print axioms SequentialFigure7.ReachableByImplementedInitNew.new
#print axioms ConclusionBelow.not_connective
#print axioms SequentialFigure7.PreparedStep.reservationInvariant
#print axioms SequentialFigure7.RulePrefix.ofPrepared
#print axioms SequentialFigure7.RulePrefix.output_unique
#print axioms SequentialFigure7.concl?_some_iff
#print axioms SequentialFigure7.ConclStep.reservationInvariant
#print axioms SequentialFigure7.concl?_reservationInvariant
#print axioms SequentialFigure7.ConclStep.toRule
#print axioms SequentialFigure7.concl?_sound
#print axioms SequentialFigure7.concl?_complete_of_structural
#print axioms SequentialFigure7.concl?_some_iff_rule_of_structural
#print axioms SequentialFigure7.ConclRule.output_unique
#print axioms SequentialFigure7.nop?_some_iff
#print axioms SequentialFigure7.NopStep.submitted_par
#print axioms ConnectiveBelow.mate_ne
#print axioms ConnectiveBelow.mate_bound
#print axioms SequentialFigure7.structural_conclusion_or_submittedConsumer_of_structural
#print axioms SequentialFigure7.NopStep.mate_unmarked_before
#print axioms SequentialFigure7.NopStep.reservationInvariant
#print axioms SequentialFigure7.nop?_reservationInvariant
#print axioms SequentialFigure7.NopStep.toRule
#print axioms SequentialFigure7.nop?_sound
#print axioms SequentialFigure7.nop?_complete_of_structural
#print axioms SequentialFigure7.nop?_some_iff_rule_of_structural
#print axioms SequentialFigure7.NopRule.output_unique
#print axioms SequentialSchedulerState.SequentialStackState.prependWaiting?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.prependWaiting?_exact
#print axioms SequentialSchedulerState.SequentialStackState.prependWaiting?_of_ne
#print axioms SequentialSchedulerState.SequentialStackState.prependWaiting?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.prependWaiting?_operationalWaitingDomain
#print axioms SequentialSchedulerState.SigmaAgePartition.popActive
#print axioms SequentialSchedulerState.SequentialStackState.prependReadyTop?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.prependReadyTop?_exact
#print axioms SequentialSchedulerState.SequentialStackState.prependReadyTop?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.prependReadyTop?_operationalWaitingDomain
#print axioms SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_some_iff
#print axioms SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_exact
#print axioms SequentialSchedulerState.SequentialStackState.MergeTopReadyWaitingStep.queuedVertices_perm
#print axioms SequentialSchedulerState.SequentialStackState.MergeTopReadyWaitingStep.mem_queuedVertices_iff
#print axioms SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_wellShaped
#print axioms SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_operationalWaitingDomain
#print axioms Certificate.queuePar?_some_iff
#print axioms Certificate.queuePar?_exact
#print axioms Certificate.queuePar?_conclusion_unmarked
#print axioms Certificate.queuePar?_reservationAlignment
#print axioms Certificate.queuePar?_abstractable
#print axioms Certificate.queuePar?_orderedParents
#print axioms Certificate.queuePar?_componentsFormulaConsistent
#print axioms Certificate.queueTensor?_some_iff
#print axioms Certificate.queueTensor?_exact
#print axioms Certificate.queueTensor?_conclusion_unmarked
#print axioms Certificate.queueTensor?_representatives_distinct
#print axioms Certificate.queueTensor?_reservationAlignment
#print axioms Certificate.queueTensor?_orderedParents
#print axioms Certificate.queueTensor?_abstractable
#print axioms Certificate.queueTensor?_componentsFormulaConsistent
#print axioms Certificate.ExactOccurrencePick.ofFirst
#print axioms Certificate.OccurrenceDerivation.usedLink_lookup
#print axioms Certificate.OccurrenceDerivation.usedLinkIndex_lt
#print axioms Certificate.OccurrenceDerivation.usedConnectiveConclusion_owned
#print axioms Certificate.OccurrenceDerivation.usedAxiomEndpoints_owned
#print axioms Certificate.OccurrenceDerivation.frontier_subset_owned
#print axioms Certificate.OccurrenceDerivation.frontier_nodup_of_owned_nodup
#print axioms Certificate.OccurrenceDerivation.owned_inBounds
#print axioms Certificate.OccurrenceDerivation.formulaConsistent
#print axioms Certificate.OccurrenceDerivation.ofQueueParStep
#print axioms Certificate.OccurrenceDerivation.ofQueueTensorStep
#print axioms Certificate.ComponentOccurrenceWitness.frontier_nodup
#print axioms Certificate.ComponentOccurrenceWitness.axiom_of_submitted
#print axioms Certificate.ComponentOccurrenceWitness.ofQueueTensorStep
#print axioms Certificate.ComponentOccurrenceWitness.referencePath_within_owned
#print axioms Certificate.ComponentForestProvenance.queueTensorStep_of_roots_fresh
#print axioms Certificate.reserveAxiomAt?_componentOccurrenceWitness
#print axioms Certificate.ExactOccurrencePick.rejects_same_formula_alias
#print axioms Certificate.ComponentForestProvenance.markReadyRaw?_of_representative_frontier
#print axioms Certificate.ComponentForestProvenance.markReadyRaw?_of_root_frontier
#print axioms Certificate.ComponentForestProvenance.liveFrontiers_nodup
#print axioms Certificate.ComponentForestProvenance.queueParStep_of_active_fresh
#print axioms Certificate.ComponentForestProvenance.queueParStep_of_root_fresh
#print axioms Certificate.ComponentForestProvenance.reserveAxiomAt?_of_fresh
#print axioms Certificate.initialUnificationState_componentForestProvenance
#print axioms Certificate.reserveAxiomAt?_componentForestProvenance_of_initial
#print axioms SequentialSchedulerBridge.InitialReservationStep.componentForestProvenance
#print axioms SequentialSchedulerBridge.enqueueWaitingAtRawAge?_some_iff
#print axioms SequentialSchedulerBridge.WaitDestinationStep.boundary_properties
#print axioms SequentialSchedulerBridge.WaitDestinationStep.exact
#print axioms SequentialSchedulerBridge.WaitDestinationStep.realizesSigma
#print axioms SequentialSchedulerBridge.WaitDestinationStep.reservationInvariant
#print axioms SequentialSchedulerBridge.enqueueWaitingAtRawAge?_reservationInvariant
#print axioms SequentialFigure7.forward?_some_iff
#print axioms SequentialFigure7.ForwardStep.submitted_par
#print axioms SequentialFigure7.ForwardStep.mate_marked_before
#print axioms SequentialFigure7.ForwardStep.reservationInvariant
#print axioms SequentialFigure7.ForwardStep.output_unique
#print axioms SequentialFigure7.ForwardStep.toRule
#print axioms SequentialFigure7.forward?_sound
#print axioms SequentialFigure7.forward?_complete_of_structural
#print axioms SequentialFigure7.forward?_some_iff_rule_of_structural
#print axioms SequentialFigure7.ForwardRule.output_unique_of_structural
#print axioms SequentialFigure7.forward?_reservationInvariant
#print axioms SequentialFigure7.SchedulerInvariant.forwardExecutableReadyNodup
#print axioms SequentialFigure7.ForwardStep.schedulerInvariant
#print axioms SequentialFigure7.forward?_schedulerInvariant
#print axioms SequentialFigure7.forward?_complete_of_schedulerInvariant
#print axioms SequentialFigure7.forward?_some_iff_rule_of_schedulerInvariant
#print axioms SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_previous_of_between
#print axioms SequentialFigure7.unifyEmpty?_some_iff
#print axioms SequentialFigure7.UnifyEmptyStep.submitted_tensor
#print axioms SequentialFigure7.UnifyEmptyStep.mate_marked_before
#print axioms SequentialFigure7.UnifyEmptyStep.realizesSigma
#print axioms SequentialFigure7.UnifyEmptyStep.toRule
#print axioms SequentialFigure7.UnifyEmptyStep.reservationInvariant
#print axioms SequentialFigure7.UnifyEmptyStep.output_unique
#print axioms SequentialFigure7.unifyEmpty?_sound
#print axioms SequentialFigure7.unifyEmpty?_reservationInvariant
#print axioms SequentialFigure7.unifyEmpty?_complete_of_structural
#print axioms SequentialFigure7.unifyEmpty?_some_iff_rule_of_structural
#print axioms SequentialFigure7.UnifyEmptyRule.output_unique_of_structural
#print axioms SequentialFigure7.UnifyEmptyStep.schedulerInvariant
#print axioms SequentialFigure7.unifyEmpty?_schedulerInvariant
#print axioms SequentialFigure7.waitingParProducer?_eq_some
#print axioms SequentialFigure7.activateWaitingPar?_some_iff
#print axioms SequentialFigure7.WaitingParActivationStep.submitted_par
#print axioms SequentialFigure7.WaitingParActivationStep.toRule
#print axioms SequentialFigure7.WaitingParActivationStep.exact
#print axioms SequentialFigure7.WaitingParActivationStep.output_unique
#print axioms SequentialFigure7.activateWaitingPar?_sound
#print axioms SequentialFigure7.activateWaitingPar?_complete
#print axioms SequentialFigure7.activateWaitingPar?_complete_of_structural
#print axioms SequentialFigure7.activateWaitingPar?_some_iff_rule
#print axioms SequentialFigure7.WaitingParActivationRule.output_unique
#print axioms SequentialFigure7.unifyOne?_some_iff
#print axioms SequentialFigure7.UnifyOneStep.submitted_tensor
#print axioms SequentialFigure7.UnifyOneStep.submitted_waiting_par
#print axioms SequentialFigure7.UnifyOneStep.mate_marked_before
#print axioms SequentialFigure7.UnifyOneStep.toRule
#print axioms SequentialFigure7.UnifyOneStep.realizesSigma
#print axioms SequentialFigure7.UnifyOneStep.reservationInvariant
#print axioms SequentialFigure7.UnifyOneStep.firedConnectives_eq_add_two
#print axioms SequentialFigure7.UnifyOneStep.tensor_then_par_components
#print axioms SequentialFigure7.UnifyOneStep.exact
#print axioms SequentialFigure7.UnifyOneStep.output_unique
#print axioms SequentialFigure7.unifyOne?_sound
#print axioms SequentialFigure7.unifyOne?_reservationInvariant
#print axioms SequentialFigure7.unifyOne?_complete_of_structural
#print axioms SequentialFigure7.unifyOne?_some_iff_rule_of_structural
#print axioms SequentialFigure7.UnifyOneRule.output_unique_of_structural
#print axioms SequentialFigure7.UnifyOneStep.schedulerInvariant
#print axioms SequentialFigure7.unifyOne?_schedulerInvariant
#print axioms SequentialFigure7.activateWaitingPayload?_some_iff
#print axioms SequentialFigure7.WaitingParActivationFoldStep.toRule
#print axioms SequentialFigure7.WaitingParActivationFoldStep.marks_eq
#print axioms SequentialFigure7.WaitingParActivationFoldStep.parents_eq
#print axioms SequentialFigure7.WaitingParActivationFoldStep.startedAxioms_eq
#print axioms SequentialFigure7.WaitingParActivationFoldStep.components_size_eq
#print axioms SequentialFigure7.WaitingParActivationFoldStep.firedConnectives_eq_add_length
#print axioms SequentialFigure7.WaitingParActivationFoldStep.abstractable
#print axioms SequentialFigure7.WaitingParActivationFoldStep.orderedParents
#print axioms SequentialFigure7.WaitingParActivationFoldStep.componentsFormulaConsistent
#print axioms SequentialFigure7.WaitingParActivationFoldStep.reservationAlignment
#print axioms SequentialFigure7.WaitingParActivationFoldStep.output_unique
#print axioms SequentialFigure7.activateWaitingPayload?_sound
#print axioms SequentialFigure7.activateWaitingPayload?_complete
#print axioms SequentialFigure7.activateWaitingPayload?_some_iff_rule
#print axioms SequentialFigure7.WaitingParActivationFoldRule.output_unique
#print axioms SequentialFigure7.unifyPayload?_some_iff
#print axioms SequentialFigure7.WaitingParActivationFoldStep.payload_vertices_lt
#print axioms SequentialFigure7.UnifyPayloadStep.submitted_tensor
#print axioms SequentialFigure7.UnifyPayloadStep.mate_marked_before
#print axioms SequentialFigure7.UnifyPayloadStep.toRule
#print axioms SequentialFigure7.UnifyPayloadStep.realizesSigma
#print axioms SequentialFigure7.UnifyPayloadStep.reservationInvariant
#print axioms SequentialFigure7.UnifyPayloadStep.firedConnectives_eq_add_one_add_length
#print axioms SequentialFigure7.UnifyPayloadStep.exact
#print axioms SequentialFigure7.UnifyPayloadStep.output_unique
#print axioms SequentialFigure7.SchedulerInvariant.withoutReady
#print axioms SequentialFigure7.UnifyPayloadGapInvariant.close
#print axioms SequentialFigure7.UnifyPayloadGapInvariant.activateHead
#print axioms SequentialFigure7.UnifyPayloadGapInvariant.WaitingParActivationFoldStep.closeGap
#print axioms SequentialFigure7.UnifyPayloadStep.schedulerInvariant
#print axioms SequentialFigure7.unifyPayload?_schedulerInvariant
#print axioms SequentialFigure7.unifyPayload?_exists_of_enabled
#print axioms SequentialFigure7.unifyPayload?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.unifyPayload?_sound
#print axioms SequentialFigure7.unifyPayload?_reservationInvariant
#print axioms SequentialFigure7.unifyPayload?_complete_of_structural
#print axioms SequentialFigure7.unifyPayload?_some_iff_rule_of_structural
#print axioms SequentialFigure7.UnifyPayloadRule.output_unique_of_structural
#print axioms SequentialFigure7.connectiveBelow_tensorBelow_eq_some
#print axioms SequentialFigure7.unifyPayload?_of_unifyEmpty?_eq_some
#print axioms SequentialFigure7.unifyPayload?_of_unifyOne?_eq_some
#print axioms SequentialFigure7.wait?_some_iff
#print axioms SequentialFigure7.WaitStep.submitted_par
#print axioms SequentialFigure7.WaitStep.mate_marked_before
#print axioms SequentialFigure7.WaitStep.reservationInvariant
#print axioms SequentialFigure7.wait?_reservationInvariant
#print axioms SequentialFigure7.WaitStep.queuedVerticesNodup
#print axioms SequentialFigure7.WaitStep.queuedVerticesUnmarked
#print axioms SequentialFigure7.WaitStep.waitingSpanExact
#print axioms SequentialFigure7.WaitStep.schedulerInvariant
#print axioms SequentialFigure7.wait?_schedulerInvariant
#print axioms SequentialFigure7.WaitDestinationStep.toWaitingPrependAt
#print axioms SequentialFigure7.WaitStep.toRule
#print axioms SequentialFigure7.wait?_sound
#print axioms SequentialFigure7.WaitingPrependAt.toExecutable
#print axioms SequentialFigure7.wait?_complete_of_structural
#print axioms SequentialFigure7.wait?_some_iff_rule_of_structural
#print axioms SequentialFigure7.WaitRule.output_unique_of_structural
#print axioms SequentialFigure7.WaitingPrependAt.output_unique
#print axioms SequentialFigure7.Figure7SuccessfulStep.schedulerInvariant
#print axioms SequentialFigure7.dispatch?_some_iff
#print axioms SequentialFigure7.DispatchStep.toSuccessfulStep
#print axioms SequentialFigure7.DispatchStep.schedulerInvariant
#print axioms SequentialFigure7.DispatchStep.output_unique
#print axioms SequentialFigure7.dispatch?_schedulerInvariant
#print axioms SequentialFigure7.initializeReservation?_schedulerInvariant
#print axioms SequentialFigure7.ExecutedHistory.schedulerInvariant
#print axioms SequentialFigure7.ConclStep.output_tags_eq
#print axioms SequentialFigure7.NopStep.output_tags_eq
#print axioms SequentialFigure7.WaitStep.output_tags_eq
#print axioms SequentialFigure7.ForwardStep.output_tags_eq
#print axioms SequentialFigure7.UnifyPayloadStep.output_tags_eq
#print axioms SequentialFigure7.DispatchStep.tagEvidence
#print axioms SequentialFigure7.DispatchTagEvidence.tagged_iff_input_or_touched
#print axioms SequentialFigure7.DispatchTagEvidence.tagsExtend
#print axioms SequentialFigure7.DispatchTagEvidence.touched_input_false
#print axioms SequentialFigure7.DispatchTagEvidence.mem_linkIndices_witness
#print axioms SequentialFigure7.DispatchTagEvidence.linkIndices_nodup
#print axioms SequentialFigure7.DispatchTagEvidence.output_tags_eq_of_kind_ne_new
#print axioms SequentialFigure7.DispatchTagEvidence.new_growth_and_singleton_link
#print axioms SequentialFigure7.DispatchTagEvidence.linkIndices_length_add_nextAge
#print axioms SequentialFigure7.ExecutedHistory.hasCanonicalTagHistory
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.hasCanonicalTagHistory
#print axioms SequentialFigure7.CanonicalTagHistory.tagged_iff_touched
#print axioms SequentialFigure7.CanonicalTagHistory.touched_history_independent
#print axioms SequentialFigure7.CanonicalTagHistory.true_tag_has_touch
#print axioms SequentialFigure7.CanonicalTagHistory.touched_persists_next
#print axioms SequentialFigure7.CanonicalTagHistory.touched_disjoint_next
#print axioms SequentialFigure7.CanonicalTagHistory.mem_linkIndices_witness
#print axioms SequentialFigure7.CanonicalTagHistory.linkIndices_nodup
#print axioms SequentialFigure7.CanonicalTagHistory.linkIndices_length_eq_nextAge
#print axioms SequentialFigure7.DispatchTagEvidence.final_rawMarked_iff_old_or_event
#print axioms SequentialFigure7.CanonicalTagHistory.final_rawMarked_iff
#print axioms SequentialFigure7.ExecutedHistory.final_rawMarked_has_event
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.final_rawMarked_has_event
#print axioms Certificate.StructurallyWellFormed.axiomEndpoint_ne_connectiveConclusion
#print axioms SequentialSchedulerBridge.InitialReservationStep.mem_queuedVertices_iff
#print axioms SequentialFigure7.PreparedStep.after_queued_subset_before
#print axioms SequentialFigure7.PrependWaitingStep.mem_queuedVertices_iff
#print axioms SequentialFigure7.PrependReadyTopStep.mem_queuedVertices_iff
#print axioms SequentialFigure7.operationalNewEnqueue?_queuedVertices_eq
#print axioms SequentialFigure7.ReadyHeadInput.rulePrefix
#print axioms SequentialFigure7.ReadyHeadInput.stack_pop_eq
#print axioms SequentialFigure7.ReadyHeadInput.core_mark_eq
#print axioms SequentialFigure7.ReadyHeadInput.stackResult_after
#print axioms SequentialFigure7.ReadyHeadInput.markedCore_carriers_aligned
#print axioms SequentialFigure7.concl?_exists_of_enabled
#print axioms SequentialFigure7.concl?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.nop?_exists_of_enabled
#print axioms SequentialFigure7.nop?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.wait?_exists_of_enabled
#print axioms SequentialFigure7.wait?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.forward?_exists_of_enabled
#print axioms SequentialFigure7.forward?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.submittedParInput_enabled_cases
#print axioms SequentialFigure7.readyHead_structural_cases
#print axioms SequentialFigure7.readyHead_enabled_or_tensor_mark_cases
#print axioms SequentialFigure7.SigmaPredecessorInput.sigma_two_levels
#print axioms SequentialFigure7.markedTensor_unifyPayloadEnabled
#print axioms SequentialFigure7.ConclStep.enabled
#print axioms SequentialFigure7.NopStep.enabled
#print axioms SequentialFigure7.WaitStep.enabled
#print axioms SequentialFigure7.ForwardStep.enabled
#print axioms SequentialFigure7.UnifyPayloadStep.enabled
#print axioms SequentialFigure7.concl?_success_iff_enabled
#print axioms SequentialFigure7.nop?_success_iff_enabled
#print axioms SequentialFigure7.wait?_success_iff_enabled
#print axioms SequentialFigure7.forward?_success_iff_enabled
#print axioms SequentialFigure7.unifyPayload?_success_iff_enabled
#print axioms SequentialFigure7.NewGuard.tensor_eq
#print axioms SequentialFigure7.NewGuard.mate_ne
#print axioms SequentialFigure7.FreshSourceLeftRoute.start_mem
#print axioms SequentialFigure7.FreshSourceLeftRoute.startFresh
#print axioms SequentialFigure7.FreshSourceLeftRoute.partner_not_mem_trace_of_structural
#print axioms SequentialFigure7.FreshSourceLeftRoute.toFreshSourceLeftRun_of_partnerOutside
#print axioms SequentialFigure7.FreshSourceLeftRoute.toFreshSourceLeftRun
#print axioms Certificate.StructurallyWellFormed.links_length_le_formulas_size
#print axioms SequentialFigure7.CanonicalTagHistory.fresh_terminal_capacity
#print axioms SequentialFigure7.ReadyHeadInput.markedStack_queued_subset_before
#print axioms SequentialFigure7.DispatchTagEvidence.queued_axiom_endpoint_old_or_touched
#print axioms SequentialFigure7.CanonicalTagHistory.queued_axiom_endpoint_touched
#print axioms SequentialFigure7.CanonicalTagHistory.fresh_run_endpoints_not_markedStack_queued
#print axioms SequentialFigure7.CanonicalTagHistory.newSourceRegionInput_of_newInput
#print axioms SequentialFigure7.CanonicalTagHistory.newEnabled_of_inputNecessary
#print axioms SequentialFigure7.CanonicalTagHistory.newEnabled_iff_inputNecessary
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.newEnabled_of_inputNecessary
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.newEnabled_iff_inputNecessary
#print axioms SequentialFigure7.NewSourceRegionInput.operationalNewReadyAt
#print axioms SequentialFigure7.NewSourceRegionInput.newEnabled
#print axioms SequentialFigure7.NewStep.coreMarked_eq_readyHeadInput
#print axioms SequentialFigure7.NewStep.stackAfter_eq_readyHeadInput
#print axioms SequentialFigure7.NewStep.mate_unmarked_before
#print axioms SequentialFigure7.NewStep.inputNecessary
#print axioms SequentialFigure7.new?_success_implies_inputNecessary
#print axioms SequentialFigure7.NewExecutableEnabled.inputNecessary
#print axioms SequentialFigure7.PriorityEnabled.newInputNecessary
#print axioms SequentialFigure7.NewEnabled.inputNecessary
#print axioms SequentialFigure7.operationalNewEnqueue?_exists_of_ready
#print axioms SequentialFigure7.NewStep.newEnabled
#print axioms SequentialFigure7.new?_success_implies_enabled
#print axioms SequentialFigure7.new?_exists_of_enabled
#print axioms SequentialFigure7.new?_success_iff_enabled
#print axioms SequentialFigure7.NewExecutableEnabled.iff_newEnabled
#print axioms SequentialFigure7.new?_exists_schedulerInvariant_of_enabled
#print axioms SequentialFigure7.PriorityEnabled.newEnabled
#print axioms SequentialFigure7.PriorityEnabled.new_of_executable
#print axioms SequentialFigure7.DispatchStep.priorityEnabled
#print axioms SequentialFigure7.PriorityEnabled.exists_dispatchStep
#print axioms SequentialFigure7.dispatch?_kind_success_iff_priorityEnabled
#print axioms SequentialFigure7.dispatch?_eq_none_iff_forall_not_priorityEnabled
#print axioms SequentialFigure7.PriorityEnabled.kind_unique
#print axioms SequentialFigure7.dispatcher_reachable_empty
#print axioms SequentialFigure7.dispatcher_reachable_of_initializeReservation?_eq_some
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.dispatch
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.schedulerInvariant
#print axioms SequentialFigure7.empty_futureWaitingUndefined
#print axioms SequentialFigure7.InitialReservationStep.futureWaitingUndefined
#print axioms SequentialFigure7.PreparedStep.futureWaitingUndefined
#print axioms SequentialFigure7.ConclStep.futureWaitingUndefined
#print axioms SequentialFigure7.NopStep.futureWaitingUndefined
#print axioms SequentialFigure7.NewStep.futureWaitingUndefined
#print axioms SequentialFigure7.WaitStep.futureWaitingUndefined
#print axioms SequentialFigure7.ForwardStep.futureWaitingUndefined
#print axioms SequentialFigure7.UnifyPayloadStep.futureWaitingUndefined
#print axioms SequentialFigure7.Figure7SuccessfulStep.futureWaitingUndefined
#print axioms SequentialFigure7.DispatchStep.futureWaitingUndefined
#print axioms SequentialFigure7.ExecutedHistory.futureWaitingUndefined
#print axioms SequentialFigure7.ReachableByImplementedDispatcher.futureWaitingUndefined
#print axioms Certificate.unificationReconstruct_accepted
#print axioms Certificate.unificationReconstruct?_sound
#print axioms Certificate.unificationReconstruct?_accepted
#print axioms Certificate.unificationWorklistReconstruct?_accepted
#print axioms Certificate.unificationWorklistFastCheck_sound
#print axioms Certificate.unificationWorklistCheck_eq_check
#print axioms Certificate.unificationWorklistCheck_eq_true_iff_check
#print axioms Certificate.unificationWorklistCheck_eq_true_iff_declarativelyCorrect
#print axioms Certificate.unificationFastCheck_eq_true_iff
#print axioms Certificate.unificationFastCheck_sound
#print axioms Certificate.unificationCheck_eq_check
#print axioms Certificate.unificationCheck_eq_true_iff_check
#print axioms Certificate.unificationCheck_eq_true_iff_declarativelyCorrect
#print axioms ExecutableSequentializationResult.kernelDerivation
#print axioms ExecutableSequentializationResult.proofNetEquivalent
#print axioms LeanProp.Derivation.toProof
#print axioms LeanProp.Derivation.linearAxiomCount_eq_length
#print axioms LeanProp.Assumptions.split_append
#print axioms LeanProp.Assumptions.permute_symm
#print axioms LeanProp.Assumptions.permute_symm_right
#print axioms LeanProp.ContextPermutation.symm_symm
#print axioms LeanProp.ContextPermutation.nonempty_iff_listPerm
#print axioms LeanProp.Derivation.persistentExchange_nonempty_of_listPerm
#print axioms LeanProp.Derivation.linearExchange_nonempty_of_listPerm
#print axioms LeanProp.Derivation.normalizePersistentStructural_reduced
#print axioms LeanProp.Derivation.normalizePersistentStructural_eq_self_of_reduced
#print axioms LeanProp.Derivation.normalizePersistentStructural_idempotent
#print axioms LeanProp.Derivation.normalizePersistentStructural_size_le
#print axioms LeanProp.Derivation.normalizePersistentStructural_contract_weaken
#print axioms LeanProp.Derivation.normalizePersistentStructural_linearAxiomCount
#print axioms LeanProp.Derivation.normalizePersistentStructural_toProof
#print axioms LeanProp.Schema.PackedDerivation.sound
#print axioms LeanProp.Schema.Raw.Derivation.infer?_ofIndexed
#print axioms LeanProp.Schema.Raw.Permutation.boundary?_eq_elaborate?
#print axioms LeanProp.Schema.Raw.Derivation.inferAt_eq_elaborateAt
#print axioms LeanProp.Schema.Raw.Derivation.elaborate?_complete
#print axioms LeanProp.Schema.Raw.CheckedDerivation.inferred
#print axioms LeanProp.Schema.Raw.CheckedDerivation.sound
