import ProofNetIR

open ProofNetIR

/-!
This file is compiled separately by the trust audit.  Its output is parsed by
`scripts/audit_axioms.py`, so adding a stronger theorem to the public logical
boundary requires an explicit update of that audit rather than a silent trust
expansion.
-/

#print axioms Certificate.check_iff_declarativelyCorrect
#print axioms Graph.IsTree.acyclic
#print axioms Graph.Acyclic.reindex
#print axioms Graph.acyclic_reindex_iff
#print axioms Graph.Acyclic.edges_add_one_le_vertexCount
#print axioms Graph.connected_of_bounded_acyclic_edgeCount
#print axioms Graph.isTree_iff_bounded_connected_acyclic
#print axioms Graph.isEdgeSimpleCycleTraversal_sound
#print axioms Graph.isEdgeSimpleCycleTraversal_complete
#print axioms Graph.hasEdgeSimpleCycle_eq_true_iff
#print axioms Graph.isAcyclic_eq_true_iff
#print axioms Graph.isTreeViaAcyclic_eq_true_iff
#print axioms Graph.isTreeViaAcyclic_eq_isTree
#print axioms Certificate.isCuspFreeTraversal_eq_true_iff
#print axioms Certificate.isCuspFreeCycleTraversal_eq_true_iff
#print axioms Certificate.hasCuspFreeEdgeSimpleCycle_eq_true_iff
#print axioms Certificate.isCuspAcyclic_eq_true_iff
#print axioms Certificate.DeclarativelyCorrect.isCuspAcyclic
#print axioms Certificate.isCuspAcyclic_of_check
#print axioms Certificate.CuspAcyclic.occurrenceSwitching_acyclic
#print axioms Certificate.cuspAcyclic_iff_allOccurrenceSwitchingsAcyclic
#print axioms Certificate.declarativelyCorrect_iff_structural_cuspAcyclic_allConnected
#print axioms Certificate.check_iff_structural_cuspAcyclic_allConnected
#print axioms Certificate.allOccurrenceSwitchingsConnected_of_reference
#print axioms Certificate.check_iff_structural_cuspAcyclic_referenceConnected
#print axioms Certificate.compactCheck_eq_check
#print axioms CutFreeDerivation.infer?_eq_some_iff_build?_conclusions
#print axioms CutFreeDerivation.build?_structurallyWellFormed
#print axioms CutFreeDerivation.build?_switchingCorrect
#print axioms CutFreeDerivation.build?_declarativelyCorrect
#print axioms CutFreeDerivation.build?_check
#print axioms CutFreeDerivation.desequentialize?_conclusionFormulas?
#print axioms CutFreeDerivation.desequentialize?_declarativelyCorrect
#print axioms CutFreeDerivation.desequentialize?_check
#print axioms CutFreeDerivation.desequentialize?_exists_with_labels_of_infer?
#print axioms CutFreeDerivation.desequentialize?_exists_checked_of_infer?
#print axioms CutFreeDerivation.desequentializeChecked?_exists_of_infer?
#print axioms CutFreeDerivation.elaborate?_exists_of_infer?
#print axioms Certificate.sequentialization_of_check
#print axioms Certificate.generallySequentializable
#print axioms Certificate.reindexEquivalent?_eq_true_iff_of_check
#print axioms Certificate.matchingFormulaOrders_complete
#print axioms Certificate.localIdentityCompatible_inverse
#print axioms Certificate.directProofNetEquivalentWitness?_complete
#print axioms Certificate.proofNetEquivalent?_eq_true_iff
#print axioms CutFreeDerivation.CheckedCertificate.sameProofNet?_eq_true_iff
#print axioms Certificate.proofNetEquivalent_iff_canonicalFamily_of_check
#print axioms Certificate.proofNetCanonicalFingerprint?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalFingerprint?_eq
#print axioms Certificate.structuralCode_injective
#print axioms Certificate.proofNetCanonicalCode?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalCode?_eq
#print axioms Certificate.proofNetEquivalent_iff_canonicalCode_of_check
#print axioms Certificate.proofNetCanonicalKey?_exists
#print axioms Certificate.ProofNetEquivalent.proofNetCanonicalKey?_eq
#print axioms Certificate.proofNetEquivalent_iff_canonicalKey_of_check
#print axioms Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit
#print axioms Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit_of_check
#print axioms Certificate.proofNetEquivalent_of_matchesCanonicalKey
#print axioms Certificate.StructurallyWellFormed.intrinsicTraversalComplete
#print axioms Certificate.StructurallyWellFormed.intrinsicOrderedLinks_perm
#print axioms Certificate.ProofNetEquivalent.intrinsicCanonicalize_eq
#print axioms Certificate.StructurallyWellFormed.intrinsicCanonicalize_proofNetEquivalent
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalize_eq_of_check
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalCode_eq_of_check
#print axioms Certificate.proofNetEquivalent_iff_intrinsicCanonicalKey_eq_of_check
#print axioms Certificate.proofNetEquivalent_of_matchesIntrinsicCanonicalKey
#print axioms Certificate.sequentialize_complete
#print axioms Certificate.verifyDerivation?_sound
#print axioms Certificate.verifyDerivation?_complete
#print axioms Certificate.reconstructDerivationWithFuel?_complete
#print axioms Certificate.reconstructDerivation?_sound
#print axioms Certificate.reconstructDerivation?_accepted
#print axioms Certificate.reconstructDerivation?_complete
#print axioms Certificate.reconstructsDerivation_eq_true_iff_check
#print axioms Certificate.reconstructsDerivation_eq_check
#print axioms Certificate.reconstructDerivationWithinLimits_sound
#print axioms Certificate.reconstructDerivationWithinLimits_accepted
#print axioms Certificate.reconstructDerivationWithinLimits_implies_reconstructs
#print axioms ExecutableSequentializationResult.kernelDerivation
#print axioms ExecutableSequentializationResult.proofNetEquivalent
#print axioms LeanProp.Derivation.toProof
#print axioms LeanProp.Derivation.linearAxiomCount_eq_length
#print axioms LeanProp.Assumptions.split_append
#print axioms LeanProp.Assumptions.permute_symm
#print axioms LeanProp.Assumptions.permute_symm_right
#print axioms LeanProp.ContextPermutation.symm_symm
#print axioms LeanProp.ContextPermutation.nonempty_iff_listPerm
#print axioms LeanProp.Derivation.persistentExchange_nonempty_of_listPerm
#print axioms LeanProp.Derivation.linearExchange_nonempty_of_listPerm
#print axioms LeanProp.Derivation.normalizePersistentStructural_reduced
#print axioms LeanProp.Derivation.normalizePersistentStructural_eq_self_of_reduced
#print axioms LeanProp.Derivation.normalizePersistentStructural_idempotent
#print axioms LeanProp.Derivation.normalizePersistentStructural_size_le
#print axioms LeanProp.Derivation.normalizePersistentStructural_contract_weaken
#print axioms LeanProp.Derivation.normalizePersistentStructural_linearAxiomCount
#print axioms LeanProp.Derivation.normalizePersistentStructural_toProof
#print axioms LeanProp.Schema.PackedDerivation.sound
#print axioms LeanProp.Schema.Raw.Derivation.infer?_ofIndexed
#print axioms LeanProp.Schema.Raw.Permutation.boundary?_eq_elaborate?
#print axioms LeanProp.Schema.Raw.Derivation.inferAt_eq_elaborateAt
#print axioms LeanProp.Schema.Raw.Derivation.elaborate?_complete
#print axioms LeanProp.Schema.Raw.CheckedDerivation.inferred
#print axioms LeanProp.Schema.Raw.CheckedDerivation.sound
