#!/usr/bin/env python3
"""Fail if the public theorem boundary silently gains trust dependencies."""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AUDIT_FILE = ROOT / "ProofNetIRAxiomAudit.lean"
EXPECTED_CLASSICAL_THEOREMS = {
    "ProofNetIR.SequentialFigure7.NewGuard.not_sourceLeftReachable_mate_head",
    "ProofNetIR.SequentialFigure7.NewGuard.terminalPartner_ne_head_of_declarativelyCorrect",
    "ProofNetIR.Certificate.OccurrenceDerivation.sourceLeftRegion_owned",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant.exactMarkedOccurrenceOwner",
    "ProofNetIR.Certificate.ComponentOccurrenceWitness.referencePath_within_owned",
    "ProofNetIR.SequentialFigure7.NewGuard.tensorConclusion_not_produced",
    "ProofNetIR.SequentialFigure7.NewGuard.tensorConclusion_not_owned",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.activeComponent",
    "ProofNetIR.SequentialFigure7.NewGuard.sourceLeftRegion_marked_representative_ne_active",
    "ProofNetIR.SequentialFigure7.ReservationEvent.leftEndpoint_sourceLeftRegion_of_touched",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.not_event_touch_of_sameRepresentative",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.rawAge_mem_sigma",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.rawAge_lt_nextAge",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.representative_eq_rawAge",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.futureWorkAt",
    "ProofNetIR.SequentialFigure7.OlderSourceRegionSeparated.not_event_touch_of_lt",
    "ProofNetIR.SequentialFigure7.SourceLeftRegionsDisjoint.eventTouchSeparated",
    "ProofNetIR.SequentialFigure7.ReservationEvent.TouchSeparatedFrom.sourceLeftRegionsDisjoint",
    "ProofNetIR.SequentialFigure7.SourceLeftRegionsDisjoint.iff_eventTouchSeparated",
    "ProofNetIR.SequentialFigure7.OlderSourceRegionSeparated.olderEventTouchSeparated",
    "ProofNetIR.SequentialFigure7.OlderEventTouchSeparated.olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.OlderEventTouchSeparated.iff_olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "event_touch_active_region_implies_representative_lt",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "event_touch_active_region_implies_rawAge_lt",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "event_touchSeparatedFrom_active_sourceLeftRegion_of_olderEventTouchSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_sourceLeftRegion_tagFresh_of_olderEventTouchSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_sourceLeftRegion_tagFresh_of_olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.ReservationEvent."
    "touched_candidateConclusion_cases",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_conclusion_touch_implies_head_touch",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_newSourceRegionInput_or_exactMarkedOwner",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_newEnabled_or_exactMarkedOwner",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_newEnabled_of_no_exactMarkedOwner",
    "ProofNetIR.SequentialFigure7.empty_olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.InitialReservationStep.olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.PreparedStep.olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.ConclStep.olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.NopStep.olderSourceRegionSeparated",
    "ProofNetIR.SequentialFigure7.OlderEventTouchSeparated."
    "strict_candidateConclusion_untouched",
    "ProofNetIR.SequentialFigure7.empty_olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.InitialReservationStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.PreparedStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.ConclStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.NopStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentEdge_referencePath_avoiding_of_strict",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentInterval_referencePath_avoiding_of_lastOlder",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.strictOlderSigmaSplit",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "sameRepresentative_conclusionTouch_decomposition",
    "ProofNetIR.SequentialFigure7.ReservationEvent."
    "touched_parConclusion_decomposition",
    "ProofNetIR.SequentialFigure7.ReservationEvent."
    "touched_parConclusion_cases",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentEdge_referencePath_avoiding_of_equal_storedRight",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentEdge_equal_boundary_dichotomy",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentEdge_parConclusion_dichotomy",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentInterval_parConclusion_dichotomy",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentInterval_parConclusion_localizedDichotomy",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceOutcome",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryTargetOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryTargetOutcome",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryMarkedOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedOutcome",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalReentryMarkedHistoricalTarget."
    "mateSeparated",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryMateSeparatedOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMateSeparatedOutcome",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalReentryMarkedMateSeparatedTarget."
    "temporalTarget",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryMarkedTemporalOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedTemporalOutcome",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalReentryMarkedMateSeparatedTemporalTarget."
    "continuationExitTarget",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryMarkedContinuationExitOutcome",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationExitOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget."
    "nopNoExactReturnTarget",
    "ProofNetIR.SequentialFigure7.NopStep."
    "commitmentInterval_parTraceReentryMarkedContinuationNoExactReturnOutcome",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain."
    "firstRepresentativeDescent_of_ne",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget."
    "firstDescentTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationFirstDescentOutcome",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore."
    "first_rawMarked",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore."
    "second_rawMarked",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.vertex_ne",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.rawMarkedPremisesBefore",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstRepresentativeDescent.causalDescent",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationFirstDescentTarget."
    "causalDescentTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationCausalDescentOutcome",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.trans",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore.asymmetric",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain."
    "rawMarkedBefore_or_eq",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent.originBeforeTerminal",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent.mateBeforeTerminal",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCausalDescentTarget."
    "terminalCausalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationTerminalCausalOutcome",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore."
    "total_of_vertex_ne",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.RawMarkedBefore."
    "eq_or_before_or_after",
    "ProofNetIR.SequentialFigure7.ContinuationExit.outerTerminalCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent."
    "siblingExitOuterTerminalCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationTerminalCausalTarget."
    "siblingExitCausalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent."
    "rawReturnCyclicJunctionOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitCausalTarget."
    "causalJunctionTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitCausalJunctionOutcome",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent."
    "rawReturnCyclicJunctionCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitCausalJunctionTarget."
    "causalEndpointTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitCausalEndpointOutcome",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionRawReturnCompleteCancellationTraversal.source_ne_base",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionRawReturnCyclicJunctionCausalOutcome.completeEndpoints",
    "ProofNetIR.SequentialFigure7.ContinuationExit.afterMarkedSibling",
    "ProofNetIR.SequentialFigure7.ContinuationExit."
    "outerTerminalForwardCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitCausalEndpointTarget."
    "forwardCausalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitForwardCausalOutcome",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionChainFirstCausalDescent.sourceExitRawOrFuture",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitForwardCausalTarget."
    "openTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitOpenOutcome",
    "ProofNetIR.SequentialFigure7.ContinuationExitRawOrFuture."
    "activeCarrierOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitOpenTarget."
    "temporalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitTemporalOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.exactSchedulerLocation",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.boundary_lt_active_of_not_owned",
    "ProofNetIR.SequentialSchedulerBridge.SchedulerInvariant."
    "mem_queued_iff_exists_futureWorkAt",
    "ProofNetIR.SequentialSchedulerBridge.SchedulerInvariant."
    "unmarkedOutsideActiveSchedulerStatus",
    "ProofNetIR.SequentialFigure7.ConnectiveBelow."
    "premisesMarked_of_futureWork",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierOutcome.scheduledOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitTemporalTarget."
    "scheduledTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitScheduledOutcome",
    "ProofNetIR.SequentialFigure7.ConnectiveBelow."
    "futureWorkPremises_causalOwnership",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactSchedulerLocation."
    "activeMateSchedulerOutcome",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierScheduledOutcome."
    "causalOwnershipOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitScheduledTarget."
    "causalOwnershipTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitCausalOwnershipOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkActiveMateSchedulerOutcome."
    "waitingOutcome_of_activeOwned",
    "ProofNetIR.SequentialFigure7.FutureWorkMateActiveCarrierScheduledStatus."
    "readyEliminatedStatus",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierCausalOwnershipOutcome."
    "readyMateOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitCausalOwnershipTarget."
    "readyMateTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitReadyMateOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkActiveMateWaitingOutcome."
    "activeCarrierParentEscape",
    "ProofNetIR.SequentialFigure7.FutureWorkActiveMateWaitingOutcome."
    "parentTemporalOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkMateActiveCarrierReadyEliminatedStatus."
    "parentRecursionStatus",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierReadyMateOutcome."
    "parentRecursionOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitReadyMateTarget."
    "parentRecursionTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitParentRecursionOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkActiveMateWaitingOutcome."
    "parentExternalTemporalOutcome",
    "ProofNetIR.SequentialFigure7.ActiveMateWaitingParentExternalTemporalOutcome."
    "commitmentReentryFailureOutcome",
    "ProofNetIR.SequentialFigure7.FutureWorkMateActiveCarrierReadyEliminatedStatus."
    "externalTemporalStatus",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierReadyMateOutcome."
    "externalTemporalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationSiblingExitReadyMateTarget."
    "externalTemporalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitExternalTemporalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryFailureHistoricalStatus."
    "markedHistoricalTarget_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "ActiveMateWaitingParentExternalCommitmentReentryFailureOutcome."
    "markedOutcome_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "FutureWorkMateActiveCarrierExternalTemporalStatus."
    "commitmentReentryMarkedStatus_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierExternalTemporalOutcome."
    "commitmentReentryMarkedOutcome_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuation"
    "SiblingExitExternalTemporalTarget."
    "waitingMarkedTarget_of_storedRight",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitWaitingMarkedOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedHistoricalTarget."
    "outerMateSeparatedTemporalTarget",
    "ProofNetIR.SequentialFigure7."
    "ActiveMateWaitingParentExternalCommitmentReentryMarkedOutcome."
    "temporalOutcome",
    "ProofNetIR.SequentialFigure7."
    "FutureWorkMateActiveCarrierExternalCommitmentReentryMarkedStatus."
    "temporalStatus",
    "ProofNetIR.SequentialFigure7."
    "ContinuationExitRawOrFutureActiveCarrierExternalCommitmentReentryMarkedOutcome."
    "temporalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuation"
    "SiblingExitWaitingMarkedTarget.temporalTarget",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "commitmentInterval_parTraceReentryMarkedContinuationSiblingExitWaitingTemporalOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedOuterMateSeparatedTemporalTarget."
    "continuationExitTarget",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedOuterMateSeparatedContinuationExitTarget."
    "waitingParentTarget",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetProducerOrientation",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "mateToTargetAvoidingPath",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateAlignedAvoidingReentry",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateAvoidingReentry",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateOuterAvoidingReentryMarkedHistoricalTarget"
    "OrContains",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateOuterAvoidingReentryMarkedHistoricalTarget"
    "OrContainsFailureHistoricalStatus",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateOuterAvoidingOrContainingReentryMarkedHistoricalTarget"
    "_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedOuterMateSeparated"
    "WaitingParentQueueStatusTarget",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedOuterMateSeparatedWaitingParentTarget."
    "queueStatusTarget",
    "ProofNetIR.SequentialFigure7.FutureWorkAtExactWaitingLocation."
    "activeTargetMateOuterWaitingParentQueueStatus_of_storedRight",
    "ProofNetIR.SequentialFigure7."
    "ActiveMateWaitingParentExternalCommitmentReentryQueueStatusOutcome",
    "ProofNetIR.SequentialFigure7."
    "ActiveMateWaitingParentExternalCommitmentReentryTemporalOutcome."
    "queueStatusOutcome",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain."
    "rawReturnCyclicReduction",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain."
    "rawReturnCyclicJunctionReduction",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationExitTarget."
    "continuationCyclicReductionTarget",
    "ProofNetIR.SequentialFigure7."
    "ActiveCarrierExternalReentryMarkedMateSeparatedContinuationCyclicReductionTarget."
    "cyclicJunctionTarget",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "strictOlder_commitmentPath_or_advance_or_equalCallbackFailure",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "strictOlder_commitmentPath_or_equalCallbackFailure",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "no_strictOlder_activeMateEventAnchor",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "event_touchSeparatedFrom_active_sourceLeftRegion",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant."
    "exactMarkedOccurrenceOwner_iff_exists_rawMark",
    "ProofNetIR.SequentialFigure7.InitialReservationStep."
    "olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.PreparedStep."
    "olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.ConclStep."
    "olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.NopStep."
    "olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.NewGuard."
    "marked_representative_le_active",
    "ProofNetIR.SequentialFigure7.OlderRawMarkedRegionSeparated."
    "active_sourceLeftRegion_no_rawMark",
    "ProofNetIR.SequentialFigure7.OlderRawMarkedRegionSeparated."
    "active_clearOwner",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_sourceLeftRegion_no_rawMark",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_sourceLeftRegion_no_exactMarkedOwner",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_sourceLeftRegion_tagFresh",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "active_newSourceRegionInput",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.active_newEnabled",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "readyHead_priorityEnabled_or_markedTensorPredecessorGap",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher."
    "readyHead_dispatch_or_markedTensorPredecessorGap",
    "ProofNetIR.SequentialFigure7.OlderMarkedTensorPredecessorInvariant."
    "readyHead_predecessor_of_boundary_lt",
    "ProofNetIR.SequentialFigure7.InitialReservationStep."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.PreparedStep."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.ConclStep."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.NopStep."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "new_olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "wait_olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "markedMate_sigmaImmediatePredecessor_of_childAnchor",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "forward_olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "unifyPayload_olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.ExecutedHistory."
    "olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher."
    "readyHead_dispatch",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant."
    "no_readyHead_iff_activeTopDrained",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher."
    "dispatch_or_activeTopDrained",
    "ProofNetIR.SequentialFigure7.InitialReservationStep."
    "activeTopMarkedNonconclusionDebt",
    "ProofNetIR.SequentialFigure7.NewStep."
    "activeTopMarkedNonconclusionDebt",
    "ProofNetIR.SequentialFigure7.ConclStep."
    "activeTopMarkedNonconclusionDebt",
    "ProofNetIR.SequentialFigure7.ForwardStep."
    "activeTopMarkedNonconclusionDebt_of_created_not_conclusion",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "activeTopMarkedNonconclusionDebt_of_created_not_conclusion",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant."
    "allMarked_of_activeTopDrained_of_nonconclusionDebt",
    "ProofNetIR.SequentialFigure7.NopStep."
    "activeTopMarkedNonconclusionDebt_iff_selectedAway",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "activeTopMarkedNonconclusionDebt_iff_selectedAway",
    "ProofNetIR.SequentialFigure7.ForwardStep."
    "activeTopMarkedNonconclusionDebt_iff_tailLaw_of_created_conclusion",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "activeTopMarkedNonconclusionDebt_iff_tailLaw_of_created_conclusion",
    "ProofNetIR.SequentialFigure7.NopStep."
    "activeTopMarkedNonconclusionDebt_iff_readyTailNonconclusion",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "activeTopMarkedNonconclusionDebt_iff_readyTailNonconclusion",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "activeTopMarkedNonconclusionDebt_of_tailLaw",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentEscape."
    "authenticMarkedPremise",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput."
    "readyTail_nonconclusion_or_parentEscape",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput."
    "parentEscape_of_no_readyTail",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentEscape."
    "temporalResidual_of_no_readyTail",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "ActiveCarrierTensorSameBoundaryResidual.temporalOutcome",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentTemporalResidual."
    "temporalOutcome",
    "ProofNetIR.SequentialFigure7.NopStep."
    "externalParentTemporalOutcome_of_no_readyTail",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "externalParentTemporalOutcome_of_no_readyTail",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "strictOlderCommitmentSplit_to_top",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentExternalTemporalOutcome."
    "commitmentOutcome",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentExternalCommitmentOutcome."
    "endpointCrossing",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentInterval_referencePath",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentExternalCommitmentOutcome."
    "reentryOutcome",
    "ProofNetIR.Certificate.OccurrenceDerivation."
    "connectivePremises_owned_of_conclusion_owned",
    "ProofNetIR.Certificate.OccurrenceDerivation."
    "connectiveConclusion_owned_of_premise_owned_not_frontier",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalEndpointReentry."
    "targetStatus",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalEndpointReentry."
    "targetFailureStatus",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalEndpointReentry."
    "targetFailureHistoricalStatus",
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalEndpointReentryAvoiding."
    "markedHistoricalTarget",
    "ProofNetIR.SequentialFigure7.InitialReservationStep."
    "markedNonconclusionContinuation",
    "ProofNetIR.SequentialFigure7.NopStep.selectedContinuationCredit",
    "ProofNetIR.SequentialFigure7.WaitStep.createdConclusionFutureWorkAt",
    "ProofNetIR.SequentialFigure7.WaitStep.selectedContinuationCredit",
    "ProofNetIR.SequentialFigure7.NewStep.selectedContinuationCredit",
    "ProofNetIR.SequentialFigure7.ForwardStep.createdConclusionFutureWorkAt",
    "ProofNetIR.SequentialFigure7.ForwardStep.selectedContinuationCredit",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "createdConclusionFutureWorkAt",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.selectedContinuationCredit",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence."
    "newlyMarkedContinuationCredit",
    "ProofNetIR.SequentialFigure7.ConclStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.NopStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.NewStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.WaitStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.ForwardStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.continuationCredit",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.oldContinuationCredit",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence."
    "markedNonconclusionContinuation",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "markedNonconclusionContinuation",
    "ProofNetIR.SequentialFigure7.FutureWorkAt."
    "rawAge_lt_active_of_activeTopDrained",
    "ProofNetIR.SequentialFigure7.ContinuationExit.elim_of_activeTopDrained",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant."
    "allMarked_of_activeTopDrained_of_continuationExitLocalized",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "not_activeTopContinuationExitLocalized",
    "ProofNetIR.SequentialFigure7.NewStep.after_representative_eq_markedMiddle",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.beforeNewOrInserted",
    "ProofNetIR.SequentialFigure7.NewStep.freshEvent_not_strictly_older",
    "ProofNetIR.SequentialFigure7.NewStep.olderSourceRegionSeparated_of_created",
    "ProofNetIR.SequentialFigure7.NewStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.NewStep."
    "created_sourceRegion_not_selected_of_structural_acyclic",
    "ProofNetIR.SequentialFigure7.NewStep."
    "created_sourceRegion_not_selected",
    "ProofNetIR.SequentialFigure7.NewStep."
    "no_middle_futureWork_at_fresh",
    "ProofNetIR.SequentialFigure7.NewStep."
    "retained_mark_strictly_older_than_fresh",
    "ProofNetIR.SequentialFigure7.NewStep."
    "created_rawMarksSeparatedFrom_of_retained",
    "ProofNetIR.SequentialFigure7.NewStep."
    "olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.beforeWaitOrInserted",
    "ProofNetIR.SequentialFigure7.WaitStep.olderSourceRegionSeparated_of_created",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.WaitStep.createdHeadTouchSeparated",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "olderEventFutureWorkTouchSeparated_of_structural",
    "ProofNetIR.SequentialFigure7.WaitStep.destination_representative_lt_selected",
    "ProofNetIR.SequentialFigure7.WaitStep."
    "created_rawMarksSeparatedFrom_of_retained",
    "ProofNetIR.SequentialFigure7.WaitStep.olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.ForwardStep.after_representative_eq_prepared",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.beforeForwardOrInserted",
    "ProofNetIR.SequentialFigure7.ForwardStep.olderSourceRegionSeparated_of_created",
    "ProofNetIR.SequentialFigure7.ForwardStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.ForwardStep.createdHeadTouchSeparated",
    "ProofNetIR.SequentialFigure7.ForwardStep."
    "olderEventFutureWorkTouchSeparated_of_structural",
    "ProofNetIR.SequentialFigure7.ForwardStep."
    "created_rawMarksSeparatedFrom_of_retained",
    "ProofNetIR.SequentialFigure7.ForwardStep.olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.after_representative_eq_prepared_if",
    "ProofNetIR.SequentialFigure7.FutureNewCandidateAt.rawAge_le_previousBoundary_of_unifyPayload",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.beforeUnifyPayloadOrMovedOrCreated",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.olderSourceRegionSeparated_of_created",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "createdConclusionTouchSeparated",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.createdHeadTouchSeparated",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep."
    "olderEventFutureWorkTouchSeparated_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "olderEventFutureWorkTouchSeparated",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshTagBlocker",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshRawBlocker",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyVisitedFreshRawBlocker",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyVisitedFreshBlocker",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshRawBlocker_of_referenceAcyclic",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshBlocker_of_referenceAcyclic",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker_of_referenceAcyclic",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.classifyFreshSourceBlocker_of_declarativelyCorrect",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_or_obstruction",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_of_no_obstruction",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.newInputNecessary_of_no_sourceLeftObstruction",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.newEnabled_of_no_sourceLeftObstruction",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.touched_nonempty_origin",
    "ProofNetIR.SequentialFigure7.CanonicalTouchOrigin.reservationRegion",
    "ProofNetIR.SequentialFigure7.ReservationEvent.touched_sourceLeftRegion",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.sourceLeftRegion_touched",
    "ProofNetIR.SequentialFigure7.ReservationEvent.sourceLeftRegion_touched",
    "ProofNetIR.SequentialFigure7.ReservationEvent.touched_iff_sourceLeftRegion",
    "ProofNetIR.SequentialFigure7.NewStep.activeRawAge_lt_reservationRawAge",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.range_append_reservationEvents",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_rawAges",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_length",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_getElem?_rawAge",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_eventAtRawAge",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_linkIndices",
    "ProofNetIR.SequentialFigure7.CanonicalTouchOrigin.reservationLedger_event",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.touched_reservationLedger_event",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.commitmentSpine",
    "ProofNetIR.CutFreeDerivation.reorder?_source_unique",
    "ProofNetIR.Certificate.OccurrenceDerivation.owned_unique",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_realized",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_finalComponent",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.reservationLedger_axiomEndpoints_accounted",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.rawMarked_reservationEvent_referenceAnchors",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.commitmentEdge_referencePath_avoiding",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory."
    "commitmentEdge_referencePath_avoiding_parConclusion",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput."
    "connectiveConclusion_not_produced",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput."
    "connectiveConclusion_not_owned_of_accounted",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.commitmentInterval_referencePath_avoiding",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.freshSourceLeftRun_carrier_not_touched",
    "ProofNetIR.SequentialFigure7.carrier_not_exactMarkedOccurrenceOwner",
    "ProofNetIR.Certificate.check_iff_declarativelyCorrect",
    "ProofNetIR.Graph.IsTree.acyclic",
    "ProofNetIR.Graph.Acyclic.edges_add_one_le_vertexCount",
    "ProofNetIR.Graph.connected_of_bounded_acyclic_edgeCount",
    "ProofNetIR.Graph.isTree_iff_bounded_connected_acyclic",
    "ProofNetIR.Graph.hasEdgeSimpleCycle_eq_true_iff",
    "ProofNetIR.Graph.isAcyclic_eq_true_iff",
    "ProofNetIR.Graph.isTreeViaAcyclic_eq_true_iff",
    "ProofNetIR.Graph.isTreeViaAcyclic_eq_isTree",
    "ProofNetIR.Certificate.hasCuspFreeEdgeSimpleCycle_eq_true_iff",
    "ProofNetIR.Certificate.isCuspAcyclic_eq_true_iff",
    "ProofNetIR.Certificate.DeclarativelyCorrect.isCuspAcyclic",
    "ProofNetIR.Certificate.isCuspAcyclic_of_check",
    "ProofNetIR.Certificate.CuspAcyclic.occurrenceSwitching_acyclic",
    "ProofNetIR.Certificate.cuspAcyclic_iff_allOccurrenceSwitchingsAcyclic",
    "ProofNetIR.Certificate.declarativelyCorrect_iff_structural_cuspAcyclic_allConnected",
    "ProofNetIR.Certificate.check_iff_structural_cuspAcyclic_allConnected",
    "ProofNetIR.Certificate.allOccurrenceSwitchingsConnected_of_reference",
    "ProofNetIR.Certificate.check_iff_structural_cuspAcyclic_referenceConnected",
    "ProofNetIR.Certificate.compactCheck_eq_check",
    "ProofNetIR.CutFreeDerivation.infer?_eq_some_iff_build?_conclusions",
    "ProofNetIR.CutFreeDerivation.build?_structurallyWellFormed",
    "ProofNetIR.CutFreeDerivation.build?_switchingCorrect",
    "ProofNetIR.CutFreeDerivation.build?_declarativelyCorrect",
    "ProofNetIR.CutFreeDerivation.build?_check",
    "ProofNetIR.CutFreeDerivation.desequentialize?_conclusionFormulas?",
    "ProofNetIR.CutFreeDerivation.desequentialize?_declarativelyCorrect",
    "ProofNetIR.CutFreeDerivation.desequentialize?_check",
    "ProofNetIR.CutFreeDerivation.desequentialize?_exists_with_labels_of_infer?",
    "ProofNetIR.CutFreeDerivation.desequentialize?_exists_checked_of_infer?",
    "ProofNetIR.CutFreeDerivation.desequentializeChecked?_exists_of_infer?",
    "ProofNetIR.CutFreeDerivation.elaborate?_exists_of_infer?",
    "ProofNetIR.Certificate.sequentialization_of_check",
    "ProofNetIR.Certificate.generallySequentializable",
    "ProofNetIR.Certificate.reindexEquivalent?_eq_true_iff_of_check",
    "ProofNetIR.Certificate.matchingFormulaOrders_complete",
    "ProofNetIR.Certificate.localIdentityCompatible_inverse",
    "ProofNetIR.Certificate.directProofNetEquivalentWitness?_complete",
    "ProofNetIR.Certificate.proofNetEquivalent?_eq_true_iff",
    "ProofNetIR.CutFreeDerivation.CheckedCertificate.sameProofNet?_eq_true_iff",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_canonicalFamily_of_check",
    "ProofNetIR.Certificate.proofNetCanonicalFingerprint?_exists",
    "ProofNetIR.Certificate.ProofNetEquivalent.proofNetCanonicalFingerprint?_eq",
    "ProofNetIR.Certificate.structuralCode_injective",
    "ProofNetIR.Certificate.proofNetCanonicalCode?_exists",
    "ProofNetIR.Certificate.ProofNetEquivalent.proofNetCanonicalCode?_eq",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_canonicalCode_of_check",
    "ProofNetIR.Certificate.proofNetCanonicalKey?_exists",
    "ProofNetIR.Certificate.ProofNetEquivalent.proofNetCanonicalKey?_eq",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_canonicalKey_of_check",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_canonicalKeyWithinLimit_of_check",
    "ProofNetIR.Certificate.proofNetEquivalent_of_matchesCanonicalKey",
    "ProofNetIR.Certificate.StructurallyWellFormed.intrinsicTraversalComplete",
    "ProofNetIR.Certificate.StructurallyWellFormed.intrinsicOrderedLinks_perm",
    "ProofNetIR.Certificate.StructurallyWellFormed.links_length_le_formulas_size",
    "ProofNetIR.Certificate.StructurallyWellFormed.freshSourceLeftRun_or_blocker",
    "ProofNetIR.Certificate.StructurallyWellFormed.freshSourceLeftRun_of_regionAvailable",
    "ProofNetIR.Certificate.ProofNetEquivalent.intrinsicCanonicalize_eq",
    "ProofNetIR.Certificate.StructurallyWellFormed.intrinsicCanonicalize_proofNetEquivalent",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_intrinsicCanonicalize_eq_of_check",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_intrinsicCanonicalCode_eq_of_check",
    "ProofNetIR.Certificate.proofNetEquivalent_iff_intrinsicCanonicalKey_eq_of_check",
    "ProofNetIR.Certificate.proofNetEquivalent_of_matchesIntrinsicCanonicalKey",
    "ProofNetIR.Certificate.sequentialize_complete",
    "ProofNetIR.Certificate.verifyDerivation?_sound",
    "ProofNetIR.Certificate.verifyDerivation?_complete",
    "ProofNetIR.Certificate.reconstructDerivationWithFuel?_complete",
    "ProofNetIR.Certificate.reconstructDerivation?_sound",
    "ProofNetIR.Certificate.reconstructDerivation?_accepted",
    "ProofNetIR.Certificate.reconstructDerivation?_complete",
    "ProofNetIR.Certificate.reconstructsDerivation_eq_true_iff_check",
    "ProofNetIR.Certificate.reconstructsDerivation_eq_check",
    "ProofNetIR.Certificate.reconstructDerivationWithinLimits_sound",
    "ProofNetIR.Certificate.reconstructDerivationWithinLimits_accepted",
    "ProofNetIR.Certificate.reconstructDerivationWithinLimits_implies_reconstructs",
    "ProofNetIR.Certificate.unificationReconstruct_accepted",
    "ProofNetIR.Certificate.unificationReconstruct?_sound",
    "ProofNetIR.Certificate.unificationReconstruct?_accepted",
    "ProofNetIR.Certificate.unificationWorklistReconstruct?_accepted",
    "ProofNetIR.Certificate.unificationWorklistFastCheck_sound",
    "ProofNetIR.Certificate.unificationWorklistCheck_eq_check",
    "ProofNetIR.Certificate.unificationWorklistCheck_eq_true_iff_check",
    "ProofNetIR.Certificate.unificationWorklistCheck_eq_true_iff_declarativelyCorrect",
    "ProofNetIR.Certificate.unificationFastCheck_eq_true_iff",
    "ProofNetIR.Certificate.unificationFastCheck_sound",
    "ProofNetIR.Certificate.unificationCheck_eq_check",
    "ProofNetIR.Certificate.unificationCheck_eq_true_iff_check",
    "ProofNetIR.Certificate.unificationCheck_eq_true_iff_declarativelyCorrect",
    "ProofNetIR.ExecutableSequentializationResult.kernelDerivation",
    "ProofNetIR.ExecutableSequentializationResult.proofNetEquivalent",
    "ProofNetIR.UnificationState.OrderedParents.startMarking_representative_eq",
    "ProofNetIR.UnificationState.OrderedParents.startMarking_sameThread_iff",
    "ProofNetIR.UnificationState.Abstractable.startMarking_ordered",
    "ProofNetIR.UnificationState.OrderedParents.toMarking_isFreshToken",
    "ProofNetIR.UnificationState.startMarking_toMarking_mark_ordered",
    "ProofNetIR.UnificationState.startMarking_startStep_ordered",
    "ProofNetIR.SequentialUnification.StructurallyWellFormed.sourceIndex_lookup_eq_singleton",
    "ProofNetIR.SequentialUnification.StructurallyWellFormed.sourceIndex_lookup_eq_submitted_par",
    "ProofNetIR.SequentialUnification.mem_sourceIndex_origin",
    "ProofNetIR.SequentialUnification.sourceIndex_sound",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_exists_of_structural_clearThrough",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_exists_of_structural_carrierClear",
    "ProofNetIR.SequentialUnification.DynamicStartResult.refinesStart",
    "ProofNetIR.Certificate.UnificationComponent.axiom?_formulaConsistent",
    "ProofNetIR.Certificate.reserveAxiomAt?_orderedParents",
    "ProofNetIR.Certificate.reserveAxiomAt?_abstractable",
    "ProofNetIR.Certificate.reserveAxiomAt?_componentsFormulaConsistent",
    "ProofNetIR.Certificate.reserveAxiomAt?_old_representative",
    "ProofNetIR.Certificate.reserveAxiomAt?_fresh_representative",
    "ProofNetIR.Certificate.reserveAxiomAt?_tokenAt_eq",
    "ProofNetIR.Certificate.reserveAxiomAt?_componentAt?_of_some",
    "ProofNetIR.SequentialSchedulerBridge.init_reserve_carrier_realizesSigma",
    "ProofNetIR.SequentialSchedulerBridge.init_reserve_route_exact",
    "ProofNetIR.SequentialSchedulerBridge.init_reserve_route_fields",
    "ProofNetIR.SequentialSchedulerBridge.empty_reservationInvariant",
    "ProofNetIR.SequentialSchedulerBridge.initializeReservation?_some_iff",
    "ProofNetIR.SequentialSchedulerBridge.reserveNewAxiom?_some_iff",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.route",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.linkIndex_ne_next",
    "ProofNetIR.SequentialSchedulerBridge.NewReservationStep.route",
    "ProofNetIR.SequentialSchedulerBridge.NewReservationStep.linkIndex_ne",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.reservationInvariant",
    "ProofNetIR.SequentialSchedulerBridge.new_reserve_carrier_realizesSigma",
    "ProofNetIR.SequentialSchedulerBridge.new_reserve_route_exact",
    "ProofNetIR.SequentialSchedulerBridge.new_reserve_route_fields",
    "ProofNetIR.SequentialSchedulerBridge.NewReservationStep.reservationInvariant",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.AllWaitingUndefined.lookup",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.initEnqueue?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.initEnqueue?_operationalWaitingDomain",
    "ProofNetIR.ConsumerIndex.build_members_eq",
    "ProofNetIR.ConsumerIndex.build_singleton",
    "ProofNetIR.ConsumerIndex.build_uniqueConsumer?_eq_some",
    "ProofNetIR.Certificate.worklistConsumers_members_eq",
    "ProofNetIR.Certificate.FirstOccurrencePick.exists_of_mem",
    "ProofNetIR.Certificate.FirstOccurrencePick.positional",
    "ProofNetIR.Certificate.FirstOccurrencePick.mem_remaining_of_ne",
    "ProofNetIR.Certificate.FirstOccurrencePick.two_of_mem",
    "ProofNetIR.Certificate.ExactOccurrencePick.ofFirst",
    "ProofNetIR.Certificate.OccurrenceDerivation.usedLink_lookup",
    "ProofNetIR.Certificate.OccurrenceDerivation.usedLinkIndex_lt",
    "ProofNetIR.Certificate.OccurrenceDerivation.usedConnectiveConclusion_owned",
    "ProofNetIR.Certificate.OccurrenceDerivation.usedAxiomEndpoints_owned",
    "ProofNetIR.Certificate.OccurrenceDerivation.frontier_subset_owned",
    "ProofNetIR.Certificate.OccurrenceDerivation.frontier_nodup_of_owned_nodup",
    "ProofNetIR.Certificate.OccurrenceDerivation.owned_inBounds",
    "ProofNetIR.Certificate.OccurrenceDerivation.formulaConsistent",
    "ProofNetIR.Certificate.OccurrenceDerivation.ofQueueParStep",
    "ProofNetIR.Certificate.OccurrenceDerivation.ofQueueTensorStep",
    "ProofNetIR.Certificate.ComponentOccurrenceWitness.frontier_nodup",
    "ProofNetIR.Certificate.ComponentOccurrenceWitness.axiom_of_submitted",
    "ProofNetIR.Certificate.ComponentOccurrenceWitness.ofQueueTensorStep",
    "ProofNetIR.Certificate.reserveAxiomAt?_componentOccurrenceWitness",
    "ProofNetIR.Certificate.ComponentForestProvenance.markReadyRaw?_of_representative_frontier",
    "ProofNetIR.Certificate.ComponentForestProvenance.markReadyRaw?_of_root_frontier",
    "ProofNetIR.Certificate.ComponentForestProvenance.liveFrontiers_nodup",
    "ProofNetIR.Certificate.ComponentForestProvenance.queueParStep_of_active_fresh",
    "ProofNetIR.Certificate.ComponentForestProvenance.queueParStep_of_root_fresh",
    "ProofNetIR.Certificate.ComponentForestProvenance.queueTensorStep_of_roots_fresh",
    "ProofNetIR.Certificate.ComponentForestProvenance.reserveAxiomAt?_of_fresh",
    "ProofNetIR.Certificate.initialUnificationState_componentForestProvenance",
    "ProofNetIR.Certificate.reserveAxiomAt?_componentForestProvenance_of_initial",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.componentForestProvenance",
    "ProofNetIR.UnificationState.markReadyRaw?_componentsFormulaConsistent",
    "ProofNetIR.SequentialSchedulerBridge.popReadyMark_markReadyRaw_reservationInvariant",
    "ProofNetIR.SequentialSchedulerBridge.empty_schedulerInvariant",
    "ProofNetIR.SequentialSchedulerBridge.SchedulerInvariant.frontier_unmarked_mem_queued",
    "ProofNetIR.SequentialSchedulerBridge.SchedulerInvariant.unmarked_liveFrontier_mem_queued",
    "ProofNetIR.SequentialSchedulerBridge.SchedulerInvariant.owned_unmarked_mem_queued",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.componentDomainExact",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.reached_ne_partner",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.liveFrontiersNodup",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.queuedVerticesNodup",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.queuedVerticesUnmarked",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.readyBucketFrontierExact",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.producedPremisesMarked",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.waitingSpanExact",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.pendingPremisesCoveredExceptReady",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.firedCounterExact",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.PreparedStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.PreparedStep.owned_unmarked_mem_after_queued",
    "ProofNetIR.SequentialFigure7.ConclStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.concl?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.NopStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.nop?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.new?_some_iff",
    "ProofNetIR.SequentialFigure7.NewStep.tensorValid",
    "ProofNetIR.SequentialFigure7.NewStep.mate_unmarked",
    "ProofNetIR.SequentialFigure7.NewStep.route",
    "ProofNetIR.SequentialFigure7.NewStep.markedMiddle_reservationInvariant",
    "ProofNetIR.SequentialFigure7.NewStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.new?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.NewStep.markedMiddle_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.NewStep.componentForestProvenance",
    "ProofNetIR.SequentialFigure7.NewStep.componentDomainExact",
    "ProofNetIR.SequentialFigure7.NewStep.liveFrontiersNodup",
    "ProofNetIR.SequentialFigure7.NewStep.readyBucketFrontierExact",
    "ProofNetIR.SequentialFigure7.NewStep.queuedVerticesNodup",
    "ProofNetIR.SequentialFigure7.NewStep.queuedVerticesUnmarked",
    "ProofNetIR.SequentialFigure7.NewStep.producedPremisesMarked",
    "ProofNetIR.SequentialFigure7.NewStep.firedCounterExact",
    "ProofNetIR.SequentialFigure7.NewStep.waitingSpanExact",
    "ProofNetIR.SequentialFigure7.NewStep.pendingPremisesCoveredExceptReady",
    "ProofNetIR.SequentialFigure7.NewStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.new?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.initial_output_tags_eq",
    "ProofNetIR.SequentialFigure7.initial_tagsExtend",
    "ProofNetIR.SequentialFigure7.NewStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.NewStep.tagsExtend",
    "ProofNetIR.SequentialFigure7.InitNewHistory.reservationInvariant",
    "ProofNetIR.SequentialFigure7.InitNewHistory.tagged_iff_touched",
    "ProofNetIR.SequentialFigure7.InitNewHistory.touched_disjoint_next",
    "ProofNetIR.SequentialFigure7.InitNewHistory.mem_linkIndices_witness",
    "ProofNetIR.SequentialFigure7.InitNewHistory.linkIndices_nodup",
    "ProofNetIR.SequentialFigure7.InitNewHistory.length_eq_nextAge",
    "ProofNetIR.SequentialFigure7.InitNewHistory.length_eq_startedAxioms",
    "ProofNetIR.SequentialFigure7.reachable_empty",
    "ProofNetIR.SequentialFigure7.reachable_of_initializeReservation?_eq_some",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedInitNew.new",
    "ProofNetIR.SequentialFigure7.PreparedStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.concl?_some_iff",
    "ProofNetIR.SequentialFigure7.ConclStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.concl?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.ConclStep.toRule",
    "ProofNetIR.SequentialFigure7.concl?_sound",
    "ProofNetIR.SequentialFigure7.concl?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.concl?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.nop?_some_iff",
    "ProofNetIR.SequentialFigure7.NopStep.submitted_par",
    "ProofNetIR.SequentialFigure7.NopStep.mate_unmarked_before",
    "ProofNetIR.SequentialFigure7.NopStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.nop?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.NopStep.toRule",
    "ProofNetIR.SequentialFigure7.nop?_sound",
    "ProofNetIR.SequentialFigure7.nop?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.nop?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialSchedulerBridge.WaitDestinationStep.reservationInvariant",
    "ProofNetIR.SequentialSchedulerBridge.enqueueWaitingAtRawAge?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.wait?_some_iff",
    "ProofNetIR.SequentialFigure7.WaitStep.submitted_par",
    "ProofNetIR.SequentialFigure7.WaitStep.mate_marked_before",
    "ProofNetIR.SequentialFigure7.WaitStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.wait?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.WaitStep.queuedVerticesNodup",
    "ProofNetIR.SequentialFigure7.WaitStep.queuedVerticesUnmarked",
    "ProofNetIR.SequentialFigure7.WaitStep.waitingSpanExact",
    "ProofNetIR.SequentialFigure7.WaitStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.wait?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.WaitStep.toRule",
    "ProofNetIR.SequentialFigure7.wait?_sound",
    "ProofNetIR.SequentialFigure7.wait?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.wait?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.WaitRule.output_unique_of_structural",
    "ProofNetIR.SequentialFigure7.forward?_some_iff",
    "ProofNetIR.SequentialFigure7.ForwardStep.submitted_par",
    "ProofNetIR.SequentialFigure7.ForwardStep.mate_marked_before",
    "ProofNetIR.SequentialFigure7.ForwardStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.ForwardStep.output_unique",
    "ProofNetIR.SequentialFigure7.ForwardStep.toRule",
    "ProofNetIR.SequentialFigure7.forward?_sound",
    "ProofNetIR.SequentialFigure7.forward?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.forward?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.ForwardRule.output_unique_of_structural",
    "ProofNetIR.SequentialFigure7.forward?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant.forwardExecutableReadyNodup",
    "ProofNetIR.SequentialFigure7.ForwardStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.forward?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.forward?_complete_of_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.forward?_some_iff_rule_of_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_some_iff",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.submitted_tensor",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.mate_marked_before",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.realizesSigma",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.toRule",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.output_unique",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_sound",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyEmptyRule.output_unique_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyEmptyStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyEmpty?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyOne?_some_iff",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.submitted_tensor",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.submitted_waiting_par",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.mate_marked_before",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.toRule",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.realizesSigma",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.firedConnectives_eq_add_two",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.tensor_then_par_components",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.exact",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.output_unique",
    "ProofNetIR.SequentialFigure7.unifyOne?_sound",
    "ProofNetIR.SequentialFigure7.unifyOne?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.unifyOne?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.unifyOne?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyOneRule.output_unique_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyOneStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyOne?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyPayload?_some_iff",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.submitted_tensor",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.mate_marked_before",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.toRule",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.realizesSigma",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.reservationInvariant",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.firedConnectives_eq_add_one_add_length",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.exact",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.output_unique",
    "ProofNetIR.SequentialFigure7.SchedulerInvariant.withoutReady",
    "ProofNetIR.SequentialFigure7.UnifyPayloadGapInvariant.close",
    "ProofNetIR.SequentialFigure7.UnifyPayloadGapInvariant.activateHead",
    "ProofNetIR.SequentialFigure7.UnifyPayloadGapInvariant.WaitingParActivationFoldStep.closeGap",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyPayload?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.unifyPayload?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.unifyPayload?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.unifyPayload?_sound",
    "ProofNetIR.SequentialFigure7.unifyPayload?_reservationInvariant",
    "ProofNetIR.SequentialFigure7.unifyPayload?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.unifyPayload?_some_iff_rule_of_structural",
    "ProofNetIR.SequentialFigure7.UnifyPayloadRule.output_unique_of_structural",
    "ProofNetIR.SequentialFigure7.unifyPayload?_of_unifyEmpty?_eq_some",
    "ProofNetIR.SequentialFigure7.unifyPayload?_of_unifyOne?_eq_some",
    "ProofNetIR.SequentialFigure7.Figure7SuccessfulStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.dispatch?_some_iff",
    "ProofNetIR.SequentialFigure7.DispatchStep.toSuccessfulStep",
    "ProofNetIR.SequentialFigure7.DispatchStep.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.DispatchStep.output_unique",
    "ProofNetIR.SequentialFigure7.dispatch?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.initializeReservation?_schedulerInvariant",
    "ProofNetIR.SequentialFigure7.ExecutedHistory.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.ConclStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.NopStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.WaitStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.ForwardStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.output_tags_eq",
    "ProofNetIR.SequentialFigure7.DispatchStep.tagEvidence",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.tagged_iff_input_or_touched",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.tagsExtend",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.touched_input_false",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.mem_linkIndices_witness",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.linkIndices_nodup",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.output_tags_eq_of_kind_ne_new",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.new_growth_and_singleton_link",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.linkIndices_length_add_nextAge",
    "ProofNetIR.SequentialFigure7.ExecutedHistory.hasCanonicalTagHistory",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.hasCanonicalTagHistory",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.tagged_iff_touched",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.touched_history_independent",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.true_tag_has_touch",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.touched_persists_next",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.touched_disjoint_next",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.mem_linkIndices_witness",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.linkIndices_nodup",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.linkIndices_length_eq_nextAge",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.final_rawMarked_iff_old_or_event",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.final_rawMarked_iff",
    "ProofNetIR.SequentialFigure7.ExecutedHistory.final_rawMarked_has_event",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.final_rawMarked_has_event",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.fresh_terminal_capacity",
    "ProofNetIR.SequentialSchedulerBridge.InitialReservationStep.mem_queuedVertices_iff",
    "ProofNetIR.SequentialFigure7.DispatchTagEvidence.queued_axiom_endpoint_old_or_touched",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.queued_axiom_endpoint_touched",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.fresh_run_endpoints_not_markedStack_queued",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.newSourceRegionInput_of_newInput",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.newEnabled_of_inputNecessary",
    "ProofNetIR.SequentialFigure7.CanonicalTagHistory.newEnabled_iff_inputNecessary",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.newEnabled_of_inputNecessary",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.newEnabled_iff_inputNecessary",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.rulePrefix",
    "ProofNetIR.SequentialFigure7.concl?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.concl?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.nop?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.nop?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.wait?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.wait?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.forward?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.forward?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.submittedParInput_enabled_cases",
    "ProofNetIR.SequentialFigure7.structural_conclusion_or_submittedConsumer_of_structural",
    "ProofNetIR.SequentialFigure7.readyHead_structural_cases",
    "ProofNetIR.SequentialFigure7.readyHead_enabled_or_tensor_mark_cases",
    "ProofNetIR.SequentialFigure7.markedTensor_unifyPayloadEnabled",
    "ProofNetIR.SequentialFigure7.ConclStep.enabled",
    "ProofNetIR.SequentialFigure7.NopStep.enabled",
    "ProofNetIR.SequentialFigure7.WaitStep.enabled",
    "ProofNetIR.SequentialFigure7.ForwardStep.enabled",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.enabled",
    "ProofNetIR.SequentialFigure7.concl?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.nop?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.wait?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.forward?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.unifyPayload?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.NewStep.coreMarked_eq_readyHeadInput",
    "ProofNetIR.SequentialFigure7.NewStep.mate_unmarked_before",
    "ProofNetIR.SequentialFigure7.NewStep.inputNecessary",
    "ProofNetIR.SequentialFigure7.new?_success_implies_inputNecessary",
    "ProofNetIR.SequentialFigure7.NewExecutableEnabled.inputNecessary",
    "ProofNetIR.SequentialFigure7.FreshSourceLeftRoute.partner_not_mem_trace_of_structural",
    "ProofNetIR.SequentialFigure7.FreshSourceLeftRoute.toFreshSourceLeftRun_of_partnerOutside",
    "ProofNetIR.SequentialFigure7.FreshSourceLeftRoute.toFreshSourceLeftRun",
    "ProofNetIR.SequentialFigure7.NewSourceRegionInput.operationalNewReadyAt",
    "ProofNetIR.SequentialFigure7.NewSourceRegionInput.newEnabled",
    "ProofNetIR.SequentialFigure7.PriorityEnabled.newInputNecessary",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.execution",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.ofExecution",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.execution_iff_nonempty",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceNodup",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceLast",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceLength",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.sourceLeftReachable",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.toFreshSourceLeftRoute_nonempty",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.stack_pop_eq",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.core_mark_eq",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.markedCore_carriers_aligned",
    "ProofNetIR.SequentialFigure7.NewStep.stackAfter_eq_readyHeadInput",
    "ProofNetIR.SequentialFigure7.NewEnabled.inputNecessary",
    "ProofNetIR.SequentialFigure7.NewStep.newEnabled",
    "ProofNetIR.SequentialFigure7.new?_success_implies_enabled",
    "ProofNetIR.SequentialFigure7.new?_exists_of_enabled",
    "ProofNetIR.SequentialFigure7.new?_success_iff_enabled",
    "ProofNetIR.SequentialFigure7.NewExecutableEnabled.iff_newEnabled",
    "ProofNetIR.SequentialFigure7.new?_exists_schedulerInvariant_of_enabled",
    "ProofNetIR.SequentialFigure7.PriorityEnabled.newEnabled",
    "ProofNetIR.SequentialFigure7.PriorityEnabled.new_of_executable",
    "ProofNetIR.SequentialFigure7.DispatchStep.priorityEnabled",
    "ProofNetIR.SequentialFigure7.PriorityEnabled.exists_dispatchStep",
    "ProofNetIR.SequentialFigure7.dispatch?_kind_success_iff_priorityEnabled",
    "ProofNetIR.SequentialFigure7.dispatch?_eq_none_iff_forall_not_priorityEnabled",
    "ProofNetIR.SequentialFigure7.PriorityEnabled.kind_unique",
    "ProofNetIR.SequentialFigure7.dispatcher_reachable_empty",
    "ProofNetIR.SequentialFigure7.dispatcher_reachable_of_initializeReservation?_eq_some",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.dispatch",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.schedulerInvariant",
    "ProofNetIR.SequentialFigure7.InitialReservationStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.ConclStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.NopStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.NewStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.WaitStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.ForwardStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.UnifyPayloadStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.Figure7SuccessfulStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.DispatchStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.ExecutedHistory.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.ReachableByImplementedDispatcher.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.componentsFormulaConsistent",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.mergeTopReadyWaiting?_operationalWaitingDomain",
    "ProofNetIR.Certificate.queuePar?_componentsFormulaConsistent",
    "ProofNetIR.Certificate.queueTensor?_abstractable",
    "ProofNetIR.Certificate.queueTensor?_componentsFormulaConsistent",
    "ProofNetIR.UnificationState.mergeConclusion_toMarking_mark",
    "ProofNetIR.UnificationState.OrderedParents.setParent_representative",
    "ProofNetIR.UnificationState.OrderedParents.setParent_sameThread",
    "ProofNetIR.UnificationState.OrderedParents.setParent_sameThread_all",
    "ProofNetIR.UnificationState.unifyTokens?_refines",
    "ProofNetIR.UnificationState.ComponentsFormulaConsistent.componentAt",
    "ProofNetIR.UnificationMarking.referencePath_has_first_marked_to_unmarked_boundary",
    "ProofNetIR.UnificationMarking.referencePath_has_last_unmarked_to_marked_boundary",
}
EXPECTED_AXIOM_FREE_THEOREMS = {
    "ProofNetIR.LeanProp.Derivation.toProof",
    "ProofNetIR.LeanProp.ContextPermutation.nonempty_iff_listPerm",
    "ProofNetIR.LeanProp.Derivation.persistentExchange_nonempty_of_listPerm",
    "ProofNetIR.LeanProp.Derivation.linearExchange_nonempty_of_listPerm",
    "ProofNetIR.UnificationCandidateResult.linkVisitsBound",
    "ProofNetIR.UnificationWorklistCandidateResult.linkAttemptsWithinBudget",
    "ProofNetIR.UnificationStep.link_exists",
    "ProofNetIR.UnificationStep.tokenCount_mono",
    "ProofNetIR.UnificationState.toMarking_tokenCount",
    "ProofNetIR.UnificationState.toMarking_mark",
    "ProofNetIR.UnificationState.toMarking_sameThread",
    "ProofNetIR.UnificationState.Abstractable.tokenAt?_bound",
    "ProofNetIR.UnificationState.tokenAt?_some_witness",
    "ProofNetIR.UnificationState.Abstractable.tokenAt?_sameThread_witness",
    "ProofNetIR.UnificationState.Abstractable.tokenAt?_root",
    "ProofNetIR.UnificationMarking.mergeExtension_equivalence",
    "ProofNetIR.UnificationExecution.trans",
    "ProofNetIR.UnificationState.ObservationEquivalent.identityParents",
    "ProofNetIR.SequentialSchedulerState.WaitingCell.undefined_ne_initialized_empty",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary_unique_of_greatest",
    "ProofNetIR.SequentialSchedulerBridge.RealizesSigma.rawAgeAt?_eq_assignedToken?",
    "ProofNetIR.SequentialFigure7.TagsExtend.refl",
    "ProofNetIR.SequentialFigure7.TagsExtend.trans",
    "ProofNetIR.SequentialUnification.nextAxiomSetTag_eq",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.stackResult_after",
}
EXPECTED_PROPEXT_ONLY_THEOREMS = {
    "ProofNetIR.SequentialFigure7.UnmarkedOutsideActiveSchedulerStatus",
    "ProofNetIR.SequentialFigure7.ActiveMateWaitingParentExternalTemporalOutcome."
    "activeCarrierOutcome",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain.terminal_marked_of_ne",
    "ProofNetIR.SequentialFigure7.MarkedConclusionChain.terminalComparable",
    "ProofNetIR.SequentialFigure7.empty_olderRawMarkedRegionSeparated",
    "ProofNetIR.SequentialFigure7.empty_olderMarkedTensorPredecessorInvariant",
    "ProofNetIR.SequentialFigure7.empty_activeTopMarkedNonconclusionDebt",
    "ProofNetIR.SequentialFigure7.empty_markedNonconclusionContinuation",
    "ProofNetIR.SequentialFigure7.LocalizedContinuationExit.continuationExit",
    "ProofNetIR.SequentialFigure7.ActiveCarrierParentExternalTemporalOutcome."
    "temporalOutcome",
    "ProofNetIR.SequentialFigure7.PreparedStep."
    "activeTopMarkedNonconclusionDebt_iff_selectedAway",
    "ProofNetIR.SequentialUnification.SourceLeftChain.reachable_to_last_of_mem",
    "ProofNetIR.SequentialFigure7.PreparedStep.after_representative_eq_before",
    "ProofNetIR.SequentialSchedulerBridge.WaitDestinationStep.after_representative_eq_before",
    "ProofNetIR.SequentialFigure7.SourceLeftRegionsDisjoint.symm",
    "ProofNetIR.CutFreeDerivation.pick?_source_unique",
    "ProofNetIR.SequentialFigure7.carrierFresh",
    "ProofNetIR.SequentialFigure7.ReservationSearchEvent.touched_sourceLeftRegion",
    "ProofNetIR.SequentialUnification.SourceLeftChain.reachable_of_head_mem",
    "ProofNetIR.SequentialUnification.NextAxiomRoute.touched_sourceLeftRegion",
    "ProofNetIR.SequentialUnification.SourceLeftReachable.eq_or_exists_lastStep",
    "ProofNetIR.SequentialFigure7.PrependReadyTopStep.mem_queuedVertices_iff",
    "ProofNetIR.SequentialFigure7.empty_futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.PreparedStep.futureWaitingUndefined",
    "ProofNetIR.SequentialFigure7.FreshSourceLeftRoute.start_mem",
    "ProofNetIR.SequentialFigure7.FreshSourceLeftRoute.startFresh",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceNonempty",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.partnerFresh",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.partner_not_mem_trace",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.exactAxiom",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.reachedReady",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.partnerReady",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceHead",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.sourceLeftChain",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceFresh",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.traceReady",
    "ProofNetIR.SequentialUnification.SourceLeftRegionVertex.prepend",
    "ProofNetIR.SequentialUnification.FreshSourceBlocker.prepend",
    "ProofNetIR.SequentialFigure7.NewGuard.mate_bound",
    "ProofNetIR.Certificate.linkLeftRetainedEdges_lookup_origin",
    "ProofNetIR.LeanProp.Derivation.linearAxiomCount_eq_length",
    "ProofNetIR.LeanProp.Assumptions.split_append",
    "ProofNetIR.LeanProp.Assumptions.permute_symm",
    "ProofNetIR.LeanProp.Assumptions.permute_symm_right",
    "ProofNetIR.LeanProp.ContextPermutation.symm_symm",
    "ProofNetIR.Certificate.isCuspFreeTraversal_eq_true_iff",
    "ProofNetIR.Certificate.isCuspFreeCycleTraversal_eq_true_iff",
    "ProofNetIR.UnificationStep.marks_fired_conclusion",
    "ProofNetIR.UnificationMarking.referenceDirectedEdge_origin",
    "ProofNetIR.UnificationMarking.marked_to_unmarked_referenceEdge_connective_origin",
    "ProofNetIR.UnificationState.Abstractable.markConclusion",
    "ProofNetIR.UnificationMarking.ext",
    "ProofNetIR.UnificationState.ObservationEquivalent.abstractable",
    "ProofNetIR.SequentialUnification.sourceIndex_size",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_sound",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_tag_trace_invariants",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_touched_tagged",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_tagged_iff_input_or_touched",
    "ProofNetIR.SequentialUnification.nextAxiom?_tagged_iff_input_or_touched",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_threaded_touched_disjoint",
    "ProofNetIR.SequentialUnification.NextAxiomResult.linkIndex_ne_of_input_left_tagged",
    "ProofNetIR.SequentialUnification.NextAxiomResult.threaded_linkIndex_ne",
    "ProofNetIR.SequentialUnification.SourceLeftChain.cons_of_head",
    "ProofNetIR.SequentialUnification.SourceLeftChain.reachable_of_head_last",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_route",
    "ProofNetIR.SequentialUnification.nextAxiom?_route",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_startReady",
    "ProofNetIR.SequentialUnification.nextAxiom?_startReady",
    "ProofNetIR.SequentialUnification.nextAxiomWithFuel?_traceReady",
    "ProofNetIR.SequentialUnification.nextAxiom?_traceReady",
    "ProofNetIR.ConsumerIndex.build_size",
    "ProofNetIR.ConsumerIndex.Sound.origin",
    "ProofNetIR.Certificate.UnificationComponent.axiom?_success",
    "ProofNetIR.SequentialSchedulerBridge.initial_realizesSigma",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary?_mem",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary?_le",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary?_append_fresh_old",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary?_popActive_of_lt",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.WellShaped.waiting_lookup_exists",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.popReadyMark?_ok_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.popReadyMark?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.initEnqueue?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.newEnqueue?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.newEnqueue?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.newEnqueue?_waiting_of_ne",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.newEnqueue?_endpoint_unmarked",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.empty_operationalWaitingDomain",
    "ProofNetIR.UnificationState.markReadyRaw?_ok_iff",
    "ProofNetIR.UnificationState.markReadyRaw?_markOutOfBounds_iff",
    "ProofNetIR.UnificationState.markReadyRaw?_alreadyMarked_iff",
    "ProofNetIR.UnificationState.markReadyRaw?_exact",
    "ProofNetIR.UnificationState.markReadyRaw?_carriers",
    "ProofNetIR.UnificationState.markReadyRaw?_counters",
    "ProofNetIR.UnificationState.markReadyRaw?_orderedParents",
    "ProofNetIR.UnificationState.markReadyRaw?_abstractable",
    "ProofNetIR.SequentialSchedulerBridge.popReadyMark_markReadyRaw_realizesSigma",
    "ProofNetIR.ConnectiveBelow.mate_ne",
    "ProofNetIR.ConnectiveBelow.mate_bound",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_reduced",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_eq_self_of_reduced",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_idempotent",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_contract_weaken",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_linearAxiomCount",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_toProof",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependWaiting?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependWaiting?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependWaiting?_of_ne",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependWaiting?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependWaiting?_operationalWaitingDomain",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.MergeTopReadyWaitingStep.queuedVertices_perm",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.MergeTopReadyWaitingStep.mem_queuedVertices_iff",
    "ProofNetIR.Certificate.queuePar?_some_iff",
    "ProofNetIR.Certificate.queuePar?_exact",
    "ProofNetIR.Certificate.queuePar?_reservationAlignment",
    "ProofNetIR.Certificate.queuePar?_abstractable",
    "ProofNetIR.Certificate.queuePar?_orderedParents",
    "ProofNetIR.Certificate.queueTensor?_some_iff",
    "ProofNetIR.Certificate.queueTensor?_exact",
    "ProofNetIR.Certificate.queueTensor?_reservationAlignment",
    "ProofNetIR.Certificate.queueTensor?_orderedParents",
    "ProofNetIR.Certificate.ExactOccurrencePick.rejects_same_formula_alias",
    "ProofNetIR.SequentialSchedulerBridge.enqueueWaitingAtRawAge?_some_iff",
    "ProofNetIR.SequentialSchedulerBridge.WaitDestinationStep.boundary_properties",
    "ProofNetIR.SequentialSchedulerBridge.WaitDestinationStep.exact",
    "ProofNetIR.SequentialSchedulerBridge.WaitDestinationStep.realizesSigma",
    "ProofNetIR.SequentialFigure7.WaitDestinationStep.toWaitingPrependAt",
    "ProofNetIR.SequentialFigure7.WaitingPrependAt.toExecutable",
    "ProofNetIR.SequentialFigure7.WaitingPrependAt.output_unique",
    "ProofNetIR.LeanProp.Schema.PackedDerivation.sound",
    "ProofNetIR.LeanProp.Schema.Raw.Derivation.infer?_ofIndexed",
    "ProofNetIR.LeanProp.Schema.Raw.Permutation.boundary?_eq_elaborate?",
    "ProofNetIR.LeanProp.Schema.Raw.CheckedDerivation.sound",
}
EXPECTED_PROPEXT_QUOT_THEOREMS = {
    "ProofNetIR.SequentialFigure7.ActiveCarrierExternalEndpointCrossing.reentry",
    "ProofNetIR.SequentialFigure7."
    "MarkedConclusionRawReturnCompleteCancellationTraversal.endpointJunctions",
    "ProofNetIR.SequentialFigure7.NewGuard.sourceLeftRegion_formulaComplexity_lt_conclusion",
    "ProofNetIR.SequentialFigure7.submittedPremise_not_conclusion",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.afterPreparedOrSelected",
    "ProofNetIR.SequentialFigure7.MarkedNonconclusionContinuation."
    "continuationExit",
    "ProofNetIR.SequentialFigure7."
    "activeTopMarkedNonconclusionDebt_of_continuationExitLocalized",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.beforePrepared",
    "ProofNetIR.SequentialFigure7.FutureNewCandidateAt.beforePrepared",
    "ProofNetIR.SequentialFigure7.FutureWorkAt.mem_queued",
    "ProofNetIR.SequentialFigure7.NewGuard.terminalPartner_ne_head",
    "ProofNetIR.SequentialUnification.SourceLeftStep.formulaComplexity_lt",
    "ProofNetIR.SequentialUnification.SourceLeftReachable.formulaComplexity_le",
    "ProofNetIR.SequentialUnification.SourceLeftRegionVertex.inBounds",
    "ProofNetIR.Certificate.StructurallyWellFormed.axiomEndpoint_ne_connectiveConclusion",
    "ProofNetIR.SequentialFigure7.PreparedStep.after_queued_subset_before",
    "ProofNetIR.SequentialFigure7.PrependWaitingStep.mem_queuedVertices_iff",
    "ProofNetIR.SequentialFigure7.operationalNewEnqueue?_queuedVertices_eq",
    "ProofNetIR.SequentialFigure7.ReadyHeadInput.markedStack_queued_subset_before",
    "ProofNetIR.SequentialFigure7.NewGuard.tensor_eq",
    "ProofNetIR.SequentialFigure7.NewGuard.mate_ne",
    "ProofNetIR.SequentialUnification.FreshSourceLeftRun.TerminalAxiom.exists_reserveAxiomAt",
    "ProofNetIR.SequentialFigure7.operationalNewEnqueue?_exists_of_ready",
    "ProofNetIR.SequentialUnification.sourceIndex_par_mem",
    "ProofNetIR.Graph.EdgeSimplePath.exists_traversed_first_boundary_of_start_true",
    "ProofNetIR.Graph.EdgeSimplePath.prefixBefore",
    "ProofNetIR.Graph.EdgeSimplePath.suffixAfter",
    "ProofNetIR.Graph.EdgeSimplePath.uniqueIntersection_of_traversal_split",
    "ProofNetIR.Graph.SimpleWalk.restrictWithSubset",
    "ProofNetIR.Graph.EdgeWalk.toSimpleWalkWithSubset",
    "ProofNetIR.Graph.EdgeWalk.toEdgeSimplePathWithVerticesSubset",
    "ProofNetIR.Graph.EdgeSimplePath.connectEraseAvoiding",
    "ProofNetIR.SequentialFigure7.sourceLeftRegionVertex_referencePath_avoiding",
    "ProofNetIR.SequentialFigure7.referenceAcyclic_no_tensorBypass",
    "ProofNetIR.UnificationMarking.referencePath_has_first_unmarked_to_marked_boundary",
    "ProofNetIR.Graph.Acyclic.reindex",
    "ProofNetIR.Graph.acyclic_reindex_iff",
    "ProofNetIR.Graph.isEdgeSimpleCycleTraversal_sound",
    "ProofNetIR.Graph.isEdgeSimpleCycleTraversal_complete",
    "ProofNetIR.LeanProp.Schema.Raw.Derivation.inferAt_eq_elaborateAt",
    "ProofNetIR.LeanProp.Schema.Raw.Derivation.elaborate?_complete",
    "ProofNetIR.LeanProp.Schema.Raw.CheckedDerivation.inferred",
    "ProofNetIR.LeanProp.Derivation.normalizePersistentStructural_size_le",
    "ProofNetIR.UnificationState.markConclusion_toMarking_mark",
    "ProofNetIR.UnificationState.markConclusion_forwardStep",
    "ProofNetIR.UnificationState.ObservationEquivalent.toMarking_eq",
    "ProofNetIR.UnificationState.forwardToken?_success",
    "ProofNetIR.UnificationState.forwardToken?_refines",
    "ProofNetIR.UnificationMarking.mergeExtension_congr",
    "ProofNetIR.UnificationMarking.mergeExtension_comm",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.empty",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.reserveInitial",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.appendFresh",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_append_fresh_self",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_top",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_top_of_le",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_popActive_eq_previous_of_active_le",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.sigmaBoundary?_eq_previous_of_between",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.popActive",
    "ProofNetIR.SequentialSchedulerState.sigmaBoundary?_greatest",
    "ProofNetIR.SequentialFigure7.SigmaPredecessorInput.sigma_two_levels",
    "ProofNetIR.SequentialSchedulerState.SigmaAgePartition.boundary_exists",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.empty_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.AllMarksUndefined.lookup",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.initEnqueue?_endpoint_unmarked",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.initEnqueue?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.newEnqueue?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.active_undefined",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.payload_boundary_lt_previous",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.OperationalWaitingDomain.payload_boundary_lt_previous_of_ne",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_endpoint_unmarked",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.operationalNewEnqueue?_operationalWaitingDomain",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependReadyTop?_some_iff",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependReadyTop?_exact",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependReadyTop?_wellShaped",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.prependReadyTop?_operationalWaitingDomain",
    "ProofNetIR.Certificate.queuePar?_conclusion_unmarked",
    "ProofNetIR.Certificate.queueTensor?_conclusion_unmarked",
    "ProofNetIR.Certificate.queueTensor?_representatives_distinct",
    "ProofNetIR.ConsumerIndex.build_origin",
    "ProofNetIR.ConsumerIndex.build_complete",
    "ProofNetIR.ConsumerIndex.build_sound",
    "ProofNetIR.ConsumerIndex.build_isComplete",
    "ProofNetIR.ConsumerIndex.uniqueConsumer?_eq_some_iff",
    "ProofNetIR.ConclusionBelow.not_connective",
    "ProofNetIR.tensorBelow?_eq_some_iff",
    "ProofNetIR.tensorBelow?_consumer",
    "ProofNetIR.tensorBelow?_link",
    "ProofNetIR.tensorBelow?_wellFormed",
    "ProofNetIR.tensorBelow?_premise",
    "ProofNetIR.tensorBelow?_mate_ne",
    "ProofNetIR.Certificate.tensorBelow?_eq_some_iff",
    "ProofNetIR.Certificate.tensorBelow?_consumer",
    "ProofNetIR.Certificate.tensorBelow?_link",
    "ProofNetIR.Certificate.tensorBelow?_wellFormed",
    "ProofNetIR.Certificate.tensorBelow?_premise",
    "ProofNetIR.Certificate.tensorBelow?_mate_ne",
    "ProofNetIR.Certificate.mem_worklistConsumers_of_premise",
    "ProofNetIR.Certificate.mem_worklistConsumers_origin",
    "ProofNetIR.Certificate.mem_worklistConsumers_submitted_connective",
    "ProofNetIR.SequentialSchedulerState.SequentialStackState.popReadyMark?_wellShaped",
    "ProofNetIR.SequentialFigure7.RulePrefix.ofPrepared",
    "ProofNetIR.SequentialFigure7.RulePrefix.output_unique",
    "ProofNetIR.SequentialFigure7.waitingParProducer?_eq_some",
    "ProofNetIR.SequentialFigure7.activateWaitingPar?_some_iff",
    "ProofNetIR.SequentialFigure7.WaitingParActivationStep.submitted_par",
    "ProofNetIR.SequentialFigure7.WaitingParActivationStep.toRule",
    "ProofNetIR.SequentialFigure7.WaitingParActivationStep.exact",
    "ProofNetIR.SequentialFigure7.WaitingParActivationStep.output_unique",
    "ProofNetIR.SequentialFigure7.activateWaitingPar?_sound",
    "ProofNetIR.SequentialFigure7.activateWaitingPar?_complete",
    "ProofNetIR.SequentialFigure7.activateWaitingPar?_complete_of_structural",
    "ProofNetIR.SequentialFigure7.activateWaitingPar?_some_iff_rule",
    "ProofNetIR.SequentialFigure7.WaitingParActivationRule.output_unique",
    "ProofNetIR.SequentialFigure7.activateWaitingPayload?_some_iff",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.toRule",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.marks_eq",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.parents_eq",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.startedAxioms_eq",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.components_size_eq",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.firedConnectives_eq_add_length",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.abstractable",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.orderedParents",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.reservationAlignment",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.output_unique",
    "ProofNetIR.SequentialFigure7.activateWaitingPayload?_sound",
    "ProofNetIR.SequentialFigure7.activateWaitingPayload?_complete",
    "ProofNetIR.SequentialFigure7.activateWaitingPayload?_some_iff_rule",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldRule.output_unique",
    "ProofNetIR.SequentialFigure7.WaitingParActivationFoldStep.payload_vertices_lt",
    "ProofNetIR.SequentialFigure7.connectiveBelow_tensorBelow_eq_some",
    "ProofNetIR.SequentialFigure7.ConclRule.output_unique",
    "ProofNetIR.SequentialFigure7.NopRule.output_unique",
    "ProofNetIR.SequentialUnification.NextAxiomRoute.orientedEndpoints?_eq",
    "ProofNetIR.Certificate.reserveAxiomAt?_exact",
    "ProofNetIR.Certificate.reserveAxiomAt?_endpoint_unmarked",
    "ProofNetIR.Certificate.reserveAxiomAt?_componentsParentsAligned",
    "ProofNetIR.Certificate.reserveAxiomAt?_counterAligned",
}
EXPECTED_THEOREMS = (
    EXPECTED_CLASSICAL_THEOREMS
    | EXPECTED_AXIOM_FREE_THEOREMS
    | EXPECTED_PROPEXT_ONLY_THEOREMS
    | EXPECTED_PROPEXT_QUOT_THEOREMS
)
EXPECTED_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}


def find_lake() -> str:
    on_path = shutil.which("lake")
    if on_path is not None:
        return on_path
    elan_bin = Path.home() / ".elan" / "bin"
    for executable in ("lake", "lake.exe"):
        candidate = elan_bin / executable
        if candidate.is_file():
            return str(candidate)
    raise FileNotFoundError("lake was not found on PATH or under ~/.elan/bin")


def main() -> None:
    completed = subprocess.run(
        [find_lake(), "env", "lean", str(AUDIT_FILE)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    output = completed.stdout + completed.stderr
    matches = re.findall(
        r"'([^']+)' depends on axioms:\s*\[([^\]]*)\]", output, re.DOTALL
    )
    actual: dict[str, set[str]] = {}
    for theorem, raw_axioms in matches:
        actual[theorem] = {
            axiom.strip() for axiom in raw_axioms.split(",") if axiom.strip()
        }
    for theorem in re.findall(
        r"'([^']+)' does not depend on any axioms", output
    ):
        actual[theorem] = set()

    if set(actual) != EXPECTED_THEOREMS:
        raise AssertionError(
            "theorem audit boundary changed: "
            f"actual={sorted(actual)}, expected={sorted(EXPECTED_THEOREMS)}\n{output}"
        )
    unexpected = {}
    for theorem, axioms in actual.items():
        if theorem in EXPECTED_AXIOM_FREE_THEOREMS:
            expected = set()
        elif theorem in EXPECTED_PROPEXT_ONLY_THEOREMS:
            expected = {"propext"}
        elif theorem in EXPECTED_PROPEXT_QUOT_THEOREMS:
            expected = {"propext", "Quot.sound"}
        else:
            expected = EXPECTED_AXIOMS
        if axioms != expected:
            unexpected[theorem] = {
                "actual": sorted(axioms),
                "expected": sorted(expected),
            }
    if unexpected:
        raise AssertionError(
            "theorem trust dependencies changed: "
            f"actual={unexpected}"
        )
    print(
        "ProofNet-IR axiom audit passed: "
        f"{len(EXPECTED_CLASSICAL_THEOREMS)} public MLL theorems use exactly "
        "[propext, Classical.choice, Quot.sound]; "
        f"{len(EXPECTED_AXIOM_FREE_THEOREMS)} additional audited theorems "
        "are axiom-free; "
        f"{len(EXPECTED_PROPEXT_ONLY_THEOREMS)} use exactly [propext]; "
        f"{len(EXPECTED_PROPEXT_QUOT_THEOREMS)} use exactly "
        "[propext, Quot.sound]"
    )


if __name__ == "__main__":
    main()
