/-
Copyright (c) 2026 ProofNet-IR contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: ProofNet-IR contributors
-/

import ProofNetIR.SequentialFigure7PriorityEnabled
import ProofNetIR.SequentialFigure7RawMarkHistory

/-!
# Figure-7 raw-mark causal order

Canonical tag history records dispatcher selections but its existing
`RawMarked` predicate forgets their chronological order.  `RawMarkedBefore`
retains the strict order generated by the recursive history: an older relation
survives one more event, while every prior event precedes the new selection.

If a submitted connective conclusion is selected, it was a live-frontier
occurrence immediately before that event.  The scheduler's causal production
field therefore shows that both submitted premises already had concrete raw
marks.  The main theorem lifts those marks to authentic earlier events.

This is an event-order checkpoint only.  It does not compare raw ages or
representatives, establish a total order, derive endpoint locality, eliminate
a continuation branch, or prove dispatcher progress.
-/

namespace ProofNetIR
namespace SequentialFigure7

open SequentialSchedulerState
open SequentialSchedulerBridge

namespace CanonicalTagHistory

/-- Strict chronological order between two authentic prepared-selection
events in one canonical dispatcher history. -/
inductive RawMarkedBefore :
    {certificate : Certificate} → {state : ReservationState} →
      {history : ExecutedHistory certificate state} →
      (tagHistory : CanonicalTagHistory certificate history) →
      RawTokenAge → Vertex → RawTokenAge → Vertex → Prop where
  | prior {certificate : Certificate} {before : ReservationState}
      {result : Figure7DispatchResult}
      {history : ExecutedHistory certificate before}
      {invariant : SchedulerInvariant certificate before}
      {dispatch : DispatchStep certificate before invariant result}
      {tagHistory : CanonicalTagHistory certificate history}
      {evidence : DispatchTagEvidence certificate before result}
      {firstAge secondAge : RawTokenAge} {first second : Vertex}
      (earlier : tagHistory.RawMarkedBefore
        firstAge first secondAge second) :
      (@CanonicalTagHistory.later certificate before result history invariant
        dispatch tagHistory evidence).RawMarkedBefore
        firstAge first secondAge second
  | current {certificate : Certificate} {before : ReservationState}
      {result : Figure7DispatchResult}
      {history : ExecutedHistory certificate before}
      {invariant : SchedulerInvariant certificate before}
      {dispatch : DispatchStep certificate before invariant result}
      {tagHistory : CanonicalTagHistory certificate history}
      {evidence : DispatchTagEvidence certificate before result}
      {firstAge secondAge : RawTokenAge} {first second : Vertex}
      (earlier : tagHistory.RawMarked firstAge first)
      (current : evidence.RawMarked secondAge second) :
      (@CanonicalTagHistory.later certificate before result history invariant
        dispatch tagHistory evidence).RawMarkedBefore
        firstAge first secondAge second

namespace RawMarkedBefore

/-- The earlier endpoint of a chronological relation is an authentic raw-mark
event in the same final history. -/
theorem first_rawMarked
    {certificate : Certificate} {state : ReservationState}
    {history : ExecutedHistory certificate state}
    {tagHistory : CanonicalTagHistory certificate history}
    {firstAge secondAge : RawTokenAge} {first second : Vertex}
    (before : tagHistory.RawMarkedBefore
      firstAge first secondAge second) :
    tagHistory.RawMarked firstAge first := by
  induction before with
  | prior earlier induction => exact Or.inl induction
  | current earlier current => exact Or.inl earlier

/-- The later endpoint of a chronological relation is an authentic raw-mark
event in the same final history. -/
theorem second_rawMarked
    {certificate : Certificate} {state : ReservationState}
    {history : ExecutedHistory certificate state}
    {tagHistory : CanonicalTagHistory certificate history}
    {firstAge secondAge : RawTokenAge} {first second : Vertex}
    (before : tagHistory.RawMarkedBefore
      firstAge first secondAge second) :
    tagHistory.RawMarked secondAge second := by
  induction before with
  | prior earlier induction => exact Or.inl induction
  | current earlier current => exact Or.inr current

/-- Strictly ordered raw-mark events select distinct occurrences. -/
theorem vertex_ne
    {certificate : Certificate} {state : ReservationState}
    {history : ExecutedHistory certificate state}
    {tagHistory : CanonicalTagHistory certificate history}
    {firstAge secondAge : RawTokenAge} {first second : Vertex}
    (before : tagHistory.RawMarkedBefore
      firstAge first secondAge second) :
    first ≠ second := by
  induction before with
  | prior earlier induction => exact induction
  | current earlier current =>
      rename_i beforeState result priorHistory invariant dispatch prior
        evidence firstAge0 secondAge0 first0 second0
      intro same
      have oldMarked :
          beforeState.core.marks[first0]? = some (some firstAge0) :=
        prior.final_rawMarked_iff.mpr earlier
      rcases UnificationState.markReadyRaw?_exact
          evidence.prepared.core_mark_eq with
        ⟨selectedUnmarked, _marksEq, _parents, _components, _started,
          _fired, _selectedMarked⟩
      have firstEqSelected :
          first0 = evidence.prepared.stackResult.vertex :=
        same.trans current.2
      rw [firstEqSelected, selectedUnmarked] at oldMarked
      simp at oldMarked

end RawMarkedBefore

private theorem mem_liveFrontierVertices_of_raw
    {state : UnificationState} {token : Nat}
    {component : UnificationComponent} {vertex : Vertex}
    (componentLookup : state.components[token]? = some (some component))
    (vertexMembership : vertex ∈ component.frontier) :
    vertex ∈ state.liveFrontierVertices := by
  unfold UnificationState.liveFrontierVertices
  apply List.mem_flatMap.mpr
  refine ⟨some component, ?_, ?_⟩
  · exact List.mem_of_getElem? (by simpa using componentLookup)
  · simpa using vertexMembership

private theorem ReadyHeadInput.produced
    {certificate : Certificate} {state : ReservationState}
    (input : ReadyHeadInput state)
    (invariant : SchedulerInvariant certificate state) :
    Produced state input.vertex := by
  rcases List.getLast?_eq_some_iff.mp input.top_ready with
    ⟨readyPrefix, readyEq⟩
  rcases List.getLast?_eq_some_iff.mp input.sigma_top with
    ⟨sigmaPrefix, sigmaEq⟩
  have lengths : readyPrefix.length = sigmaPrefix.length := by
    have aligned := invariant.stack_wellShaped.ready_aligned
    rw [readyEq, sigmaEq] at aligned
    simp at aligned
    omega
  have sigmaLookup :
      state.stack.sigma[readyPrefix.length]? = some input.rawAge := by
    rw [sigmaEq]
    simp [lengths]
  have readyLookup :
      state.stack.ready[readyPrefix.length]? =
        some (input.vertex :: input.readyTail) := by
    rw [readyEq]
    simp
  rcases invariant.ready_bucket_frontier_exact sigmaLookup readyLookup with
    ⟨component, componentLookup, exactMembership⟩
  have frontier : input.vertex ∈ component.frontier :=
    (exactMembership input.vertex).mp (by simp) |>.1
  exact Or.inr
    (mem_liveFrontierVertices_of_raw componentLookup frontier)

/-- Both submitted premises of an authentically raw-marked connective
conclusion were authentically raw-marked at strictly earlier dispatcher
events. -/
theorem rawMarkedPremisesBefore
    {certificate : Certificate} {state : ReservationState}
    {history : ExecutedHistory certificate state}
    (tagHistory : CanonicalTagHistory certificate history)
    {vertex : Vertex} (consumer : ConnectiveBelow certificate vertex)
    {conclusionAge : RawTokenAge}
    (conclusionEvent :
      tagHistory.RawMarked conclusionAge consumer.conclusion) :
    ∃ premiseAge mateAge,
      tagHistory.RawMarkedBefore premiseAge vertex
          conclusionAge consumer.conclusion ∧
        tagHistory.RawMarkedBefore mateAge consumer.mate
          conclusionAge consumer.conclusion := by
  induction tagHistory with
  | empty => exact False.elim conclusionEvent
  | init step => exact False.elim conclusionEvent
  | @later before result history invariant dispatch prior evidence ih =>
      rcases conclusionEvent with oldEvent | currentEvent
      · rcases ih oldEvent with
          ⟨premiseAge, mateAge, premiseBefore, mateBefore⟩
        exact ⟨premiseAge, mateAge, RawMarkedBefore.prior premiseBefore,
          RawMarkedBefore.prior mateBefore⟩
      · have produced : Produced before consumer.conclusion := by
          rw [currentEvent.2]
          simpa [PreparedStep.readyHeadInput] using
            ReadyHeadInput.produced evidence.prepared.readyHeadInput invariant
        have linkMembership :
            consumer.submittedLink ∈ certificate.links :=
          List.mem_of_getElem? consumer.link_eq
        have premises :=
          invariant.produced_premises_marked linkMembership
        cases sideEq : consumer.side <;> cases kindEq : consumer.kind
        all_goals
          simp [ConnectiveBelow.submittedLink,
            SequentialConnectiveKind.asLink, kindEq] at premises
        all_goals
          rcases premises produced with
            ⟨⟨leftAge, leftMarked⟩, rightAge, rightMarked⟩
        · refine ⟨leftAge, rightAge, ?_, ?_⟩
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                have vertexEq : vertex = consumer.storedLeft := by
                  simpa [TensorPremiseSide.premise, sideEq] using
                    consumer.premise_eq
                rw [vertexEq]
                exact leftMarked))
              currentEvent
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                simpa [ConnectiveBelow.mate, TensorPremiseSide.mate, sideEq]
                  using rightMarked)) currentEvent
        · refine ⟨leftAge, rightAge, ?_, ?_⟩
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                have vertexEq : vertex = consumer.storedLeft := by
                  simpa [TensorPremiseSide.premise, sideEq] using
                    consumer.premise_eq
                rw [vertexEq]
                exact leftMarked))
              currentEvent
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                simpa [ConnectiveBelow.mate, TensorPremiseSide.mate, sideEq]
                  using rightMarked)) currentEvent
        · refine ⟨rightAge, leftAge, ?_, ?_⟩
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                have vertexEq : vertex = consumer.storedRight := by
                  simpa [TensorPremiseSide.premise, sideEq] using
                    consumer.premise_eq
                rw [vertexEq]
                exact rightMarked))
              currentEvent
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                simpa [ConnectiveBelow.mate, TensorPremiseSide.mate, sideEq]
                  using leftMarked)) currentEvent
        · refine ⟨rightAge, leftAge, ?_, ?_⟩
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                have vertexEq : vertex = consumer.storedRight := by
                  simpa [TensorPremiseSide.premise, sideEq] using
                    consumer.premise_eq
                rw [vertexEq]
                exact rightMarked))
              currentEvent
          · exact RawMarkedBefore.current
              (prior.final_rawMarked_iff.mp (by
                simpa [ConnectiveBelow.mate, TensorPremiseSide.mate, sideEq]
                  using leftMarked)) currentEvent

end CanonicalTagHistory
end SequentialFigure7
end ProofNetIR
